EDCD/EDDI

- DataDefinitions/Body.cs
- EDDI/EDDI.cs
Add reserve level to body object, to allow reporting to other 3rd party sources. Issue #97 noted that this is missing
> Add body reserves to body object

- DataDefinitions/Ship.cs
- EDDI/ChangeLog.md
- ShipMonitor/ConfigurationWindow.xaml
- ShipMonitor/FrontierApi.cs
- ShipMonitor/ShipMonitor.cs
#146
EDDI will now only selectively take a complete raw json (the partial json provided when the ship is not the primary is ignored). Furthermore, the 'Export to Coriolis' button will now be disabled if EDDI doesn't have the data for an export.
> Bugfix for #146 - Export to Coriolis

- EDDI/ChangeLog.md
- StarMapService/StarMapService.cs
Fix for #161
The URI generated from the detailed raw given by the API may be very long. Testing seems to put the maximum length that EDSM can support at around 8192 characters, so if the URI exceeds this limit then the Coriolis URI is suppressed.
> Fix for EDSM rejecting long URIs

- CompanionAppService/CompanionAppService.cs
- Contributors.md
- EDDI/EDDI.cs
API data retrieval performance improved by splitting data queries into two functional parts.
refreshProfile() handles commander, ships, and system/station data via API /profile query.
conditionallyRefreshProfile() handles station services data via API /market and /shipyard queries.. Method is called specifically for 'Location' & 'Docked' events. A dedicated thread is 'spun off', which mitigates the 5 sec delay required for collecting shipyard (ships available for purchase) data.
> API data retrieval performance

- EDDI/ChangeLog.md
- EDDI/EDDI.csproj
- EDDI/MainWindow.xaml
- EDDI/MainWindow.xaml.cs
Revised bug reporting to address issue #91.
The button now routes users to a new Github issue.
If verbose logging is enabled, a truncated log (1 hour max) is zipped and dropped onto the desktop so that it can be attached to the new issue at the user's option.
Updated to better handle timezone issues in parsing. Replaces PR #166.
> Feature - Revamped bug reporting (revised)

- DataDefinitions/Material.cs
- DataDefinitions/MaterialAmount.cs
- EDDI/ChangeLog.md
- EDSMResponder/EDSMResponder.cs
- Events/MaterialCollectedEvent.cs
- Events/MaterialDiscardedEvent.cs
- Events/MaterialDiscoveredEvent.cs
- Events/MaterialDonatedEvent.cs
- MaterialMonitor/MaterialMonitor.cs
- MaterialMonitor/MaterialMonitorConfiguration.cs
This should be safe, but backup your materialsmonitor.json before testing just in case.
- Revises the material so that it consistently uses the edname as a key, rather than using a mixture of the material name and the material edname (collectively: material). Add edname to the json.
- Preserves current user settings while converting to the new edname version of the json
- Adds a DeprecatedMaterials function to Materials.cs to identify and prune old data (this will be obsolete / no longer required once everyone is transitioned from the current json format)
- Revises logic to make the materialsmonitor more "self-healing". The 1st time is is run it'll add an EDName to all of the entries in materialmonitor.json. The 2nd time, it'll identify any entries with the duplicate EDNames and select …
> Bugfix for #83 - materialsmonitor

- EDDI/ChangeLog.md
- EDDI/MainWindow.xaml.cs
- Installer.iss
- Utilities/Constants.cs
Bugfix for #184. ensures output of "linedate" is in UTC and prevents the creation of a truncated log zip file if the algorithm returns zero matches. See also comments on commit https://github.com/EDCD/EDDI/commit/c0f89725803e100b3949f7649372e95e40344258 for rational on this change.
> Fix for #184, empty truncated error logs

- Contributors.md
- EDDI/ChangeLog.xaml.cs
- LICENSE.md
- README.md
- SpeechResponder/HelpWindow.xaml.cs
- SpeechResponder/VariablesWindow.xaml.cs
- TROUBLESHOOTING.md
- VoiceAttack.md
My take on PR #188. Re-saved .md files with UTF-8 encoding and added 'html = "<head>  <meta charset=\"UTF-8\"> </head> " + html;' to html headers. From my testing, this solution appears to work well.
> International characters & UTF formatting

- EDDI/ChangeLog.md
- SpeechService/SpeechService.cs
Fix for #208. 
Beta testing this change is recommended so that it can be tested with variety of Cereproc voices.
This solution currently works for: `CereVoice Heather - English (Scotland)`
> Fix for Cereproc voice selection not respected / reverting to Windows system default

- EDDI/ChangeLog.md
- Events/StarScannedEvent.cs
- Installer.iss
- JournalMonitor/JournalMonitor.cs
- Utilities/Constants.cs
Fix for #213. We updated the script to handle the way age is reported from the server by multiplying by 1,000,000 there, but the age reported from the journal is already multiplied by 1,000,000 so it's compounding, making every star impossibly old.
> Stellar age fix

- EDDI/EDDIConfiguration.cs
- StarMapService/StarMapConfiguration.cs
I have noticed with issues #218, #222, & #223 that the files causing EDDI to crash after upgrades seem to be the same files where I added new keys in recent updates. So I'm adding some default values in the hope of preventing future similar crashes.
> Possible fixes for crashing after updating to the latest version

- DataDefinitions/StarClass.cs
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- Events/BodyScannedEvent.cs
- Events/StarScannedEvent.cs
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/ShipMonitor.cs
- SpeechResponder/eddi.json
- Utilities/Constants.cs
Adds calculated variables to the 'Body scanned' and 'Star scanned' events containing the estimated value of the scan and, for stars, the estimated habitable zone for that star system.
I've been doing both of these calculations via Cottle scripts for a while now, but PR #207 prompted me to incorporate them as calculated variables that can be made more accessible to others.
Calculation results tested against EDDiscovery and look good. :-)
> Exploration: Scan calculations

- EDDI/ChangeLog.md
- SpeechResponder/eddi.json
Update scripts for refueling per #175 to eliminate the repetition of the old 'Ship refueled' event for every 5T refueled and to add some variety to the output. EDDI will also now provide better warnings for low fuel.
> Updating the refueling script

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- GalnetMonitor/GalnetMonitor.cs
- JournalMonitor/JournalMonitor.cs
Fix for #265 to ensure that 'Fileheader' events do not trigger the Galnet Monitor.
Revised EDDI.Instance.JournalTimeStamp to no longer be a nullable value.
> Galnet updating - refinements

- EDDI/ChangeLog.md
- SpeechResponder/Personality.cs
- SpeechResponder/eddi.json
Fix for #277. The script name of 'Crew member role change' was mismatched with the key: 'Crew member role changed', causing EDDI to fail to lookup the script correctly.
Since the old script had to be removed so that a new script with the same key but a different script name could be written, I also deprecated and removed the 'Jumping' event that JGM retired some time ago.
> Correct 'Crew member role changed' script

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
Update as requested per #122 to honour changes to home systems and stations immediately upon changing the EDDI configuration, rather than after an app restart.
> Honour changes to home system and station immediately

- Events/MissionCompletedEvent.cs
Adds two variables for VoiceAttack to describe the mission commodity reward (if rewarded).
_{TXT:EDDI mission completed rewardCommodity}_ and _{INT:EDDI mission completed rewardAmount}_
The commodity reward is  passed to the Speech Responder in a list of objects, so is unavailable to VA. I don't know why, I searched through 5 months of journal logs and couldn't find an instance of being rewarded more than one type of commodity for a mission. 
Perhaps the game did in the past, or the material reward was once combined with the commodity (It appears now to be sent as a separate MaterialCollected event when you turn in the mission) 
At any rate, these changes will assign the values of the first commodity in that list to the VA variables. 
I think this is the last piece of the puzzle to having …
> Modify Mission Completed Event

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- Events/EddiEvents.csproj
- Events/VehicleDestroyedEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.json
Update per #285, improving vehicle tracking and adding a 'Vehicle destroyed' event. In testing, this event appears to always trigger for fighter destruction. It also occasionally triggers for SRV destruction.
> Vehicle destroyed event

- EDDI/ChangeLog.md
- SpeechService/SpeechService.cs
Today I stumbled across this article: https://msdn.microsoft.com/en-us/library/hh378389(v=office.14).aspx
After doing some testing, I found that Cereproc accepts the two letter country codes (en) but not the more traditional country/region codes (EN-GB). This change eliminates exceptions from the speech synthesizer for the xml:lang tag being undefined and consequently improves SSML support for Cereproc voices.
Consider this an update on issue #208.
> Improved Cereproc support

- EDDI/ChangeLog.md
- ShipMonitor/ConfigurationWindow.xaml.cs
- ShipMonitor/ShipMonitor.cs
Fix #305 by checking to make sure all dispatcher actions are completed prior to writing to the shipyard.
Though this solution works, there may be a more elegant way to code this (perhaps using Dispatcher.CurrentDispatcher.Hooks.DispatcherInactive)?
> Fix dispatcher timing for writing shipyard data

- EDDI/App.config
- EDDI/ChangeLog.md
- EDDI/EDDI.csproj
- EDDI/MainWindow.xaml.cs
- EDDI/Properties/Settings.Designer.cs
- EDDI/Properties/Settings.settings
Big fan of EDDI. EDDI-2.4.6-b2 working well, but I have a dual monitor setup and the saved window position/size would always render on the primary monitor, instead of the second monitor where EDDI and/or VoiceAttack are usually run from.
Hope this code (or portions) can help move the EDDI project forward.
> Multi monitor size position

- EDDI/MainWindow.xaml
- EDDI/MainWindow.xaml.cs
- README.md
- TROUBLESHOOTING.md
Guidance on fixing common issues should be more readily available, but is currently buried within a link from ReadMe.md where it can easily be missed and is rarely updated.
This change adds a UI link to troubleshooting.md and updates the information available in both ReadMe.md and troubleshooting.md.
> Troubleshooting

- EDDI/ChangeLog.md
- SpeechService/SpeechService.cs
- Tests/SpeechTests.cs
Revise TTS distortion effect per #326.
Make the distortion effect a modifier that increases the level of voice processing, rather than a separate effect. Thus, the effects level set by the user becomes a floor and the actual effects level increases with damage to the ship if this option is enabled.
Also adjusted audio gain for volume loss that occurs as the effects level increases.
> Text-to-Speech distortion effects

- Utilities/Net.cs
Fix for #352.
This function is used to retrieve material uses and blueprint info from the server.
Any error with parsing this data would throw an exception. The full contents do need not be included in the log.
> Omit the contents of generic web responses from the debug log

- DataDefinitions/ModuleDefinitions.cs
- EDDI/ChangeLog.md
Add decontamination limpets to module definitions and assign missing eddb ids for type 10 Defender
> Fix for #362

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- ShipMonitor/ShipMonitor.cs
- SpeechResponder/EddiSpeechResponder.csproj
- SpeechResponder/SpeechResponder.cs
- StatusMonitor/StatusMonitor.cs
- VoiceAttackResponder/EddiVoiceAttackResponder.csproj
- VoiceAttackResponder/VoiceAttackPlugin.cs
Fix for #395. VoiceAttack receives events again. The status monitor is more contained than it was before.
> Hotfix 395 voiceattack events

- DataProviderService/StarSystemSqLiteRepository.cs
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDSMResponder/ConfigurationWindow.xaml.cs
- EDSMResponder/EDSMResponder.cs
- StarMapService/StarMapService.cs
and now batch processes / writes sync data to its database as suggested in #407.
> Fix for #407. EDDI will no longer try to sync your full flight log every time it loads

- StatusMonitor/StatusMonitor.cs
Tweaked logic so that entering masslock while charging the fsd won't result in a "charging complete" message (and similar)
> Shift "instant" fsd status messages to appear only in events and not in the status object.

- EDDI/ChangeLog.md
- ShipMonitor/ShipMonitor.cs
Verified that shipmonitor.json is being updated, EDDI's UI is being updated, and that no exceptions are thrown. Please test and confirm! :-)
- The shipyard now uses BindingOperations.EnableCollectionSynchronization to synchronize the collection between threads (note that the shipmonitor is not run on the same thread when used as a plugin from VoiceAttack and requires the use of the dispatcher to initiate the sync.
- Removed `uiSyncContext`. No longer required.
- Added `ShipyardUpdatedEvent`. This can be used to "force" a UI refresh (though it typically is not needed)
- Revised sequencing to prevent a lock from being called while already inside a lock. 
- Unrelated improvement: The `refreshProfileDelayed` method is now an async Task method, rather than an async void method.
> Fix for #305. Run actions to update the shipmonitor in the dispatcher thread.

- StatusMonitor/StatusMonitor.cs
FD's _Status.json_ text is "FireGroup", typo'ed in StatusMonitor.cs as "Firegroup" 
Causes variable {INT:Status firegroup} to be returned as unset.
_Example data from Status.json_
{ "timestamp":"2018-03-10T19:14:50Z", "event":"Status", "Flags":16777224, "Pips":[4,4,4], "FireGroup":1, "GuiFocus":0 }
> Fix FireGroup typo

- EDDI/ChangeLog.md
- Installer.iss
Fix #429 by enhancing the InnoSetup script.
Note to testers: upgrade installations will continue to use whatever location the user set in the first installation. So to test this you will need to uninstall EDDI from the Apps control panel (back up your %APPDATA%\EDDI dir first!).
> #429 make installer respect any custom VoiceAttack location

- EDDI/ChangeLog.md
- SpeechService/SpeechService.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
Sets a variable in VoiceAttack to indicate whether EDDI is speaking at the moment. For synchronizing text to speech between EDDI and other sources.
Fix for #34.
> Set a variable in VoiceAttack whenever EDDI speaks

- VoiceAttackResponder/VoiceAttackPlugin.cs
The VoiceAttack variable for the commander's title was not being initialised. Fixed.
> Initialise cmdr title

- EDDNResponder/EDDNResponder.cs
- Tests/EddnTests.cs
Add a sanity check to make sure that the system name during the `Docked` matches the system name and coordinates that the EDDN Responder is referencing. If the two do not match, fall back to the StarSystemSqlLiteRepository or null the values and do not send.
> EDDN `Docked` Event - sanity check

- JournalMonitor/JournalMonitor.cs
Anthor alerted me that the `Module arrived` and `Ship arrived` events were being passed to EDSM.
This occured because the old method of generating the events created a "raw" event, and events with a "raw" are sent to EDSM. Fixed by generating the events as synthetic events, without a "raw" property.
> Prevent synthetic events sent to EDSM

- CargoMonitor/CargoMonitor.cs
- DataDefinitions/Material.cs
- EDDI/ChangeLog.md
- Events/EddiEvents.csproj
- Events/MaterialTradedEvent.cs
- Events/TechnologyBrokerEvent.cs
- JournalMonitor/JournalMonitor.cs
- MaterialMonitor/MaterialMonitor.cs
- SpeechResponder/eddi.json
Fix for #453.
Adds new 'MaterialTrade` and `TechnologyBroker` events
Replaces #462 (resubmitted to slightly clean the commit history).
> Material event updates (resubmitted)

- Tests/BodyScanTests.cs
- Tests/BuildTests.cs
- Tests/CommanderDataTests.cs
- Tests/CommodityTests.cs
- Tests/CoriolisTests.cs
- Tests/DataDefinitionTests.cs
- Tests/DataProviderTests.cs
- Tests/DiffTests.cs
- Tests/EddnTests.cs
- Tests/GeneratorTests.cs
- Tests/JournalMonitorTests.cs
- Tests/PromotionTests.cs
- Tests/ScriptResolverTest.cs
- Tests/ShipTests.cs
- Tests/SpeechTests.cs
- Tests/StarSystemDataTests.cs
- Tests/StatusMonitorTests.cs
- Tests/TranslationTests.cs
- Tests/VersioningTests.cs
- Tests/VoiceAttackPluginTests.cs
Separated the tests by namespace into "UnitTests", "SpeechTests" and "GeneratorTests".
This makes it easy to select a group to run when the Test Explorer is in hierarchy view.
> #70 use namespaces to distinguish the various types of test

- SpeechResponder/Personality.cs
This was killing performance at startup for me due to being called very repeatedly (I have a handful of legacy personality scripts) to the point where a regular user would think the app had crashed. I'm talking over a minute to launch the app, hence the label I've assigned.
Reducing to `Logging.Info()` solved it completely.
I assess the risk as minimal.
> Log missing speech scripts at info level, not report

- Utilities/Logging.cs
If passed a List<>, this code generates an exception.
Wrapping the passed-in object in a one-element dictionary solves the problem.
> Amend code where data is not a JSON dictionary

- StatusMonitor/StatusMonitor.cs
(Based on the data provided, the status monitor appears to be attempting to parse an empty string / uninitialized object)
> Improve data collection and attempt to resolve rollbar item #10 & 11.

- Utilities/Files.cs
- Utilities/Logging.cs
And demote Files.Read() errors to Debug level reporting.
> Scrub data directory file paths from Rollbar reporting.

- JournalMonitor/JournalMonitor.cs
Fix for rollbar#99.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at EddiJournalMonitor.JournalMonitor.ParseJournalEntry(String line)
```
> Fix unparseable null values passed from journal reader

- JournalMonitor/JournalMonitor.cs
- Tests/JournalMonitorTests.cs
The friends event should be triggering when
1. A friend is already being tracked on our list (the initial rush of events when you log in populates the list, index > 0) and
2. There is a change in the status of that friend (friends[index].status != cmdr.status).
Looks like we may have got this a bit backwards previously during an editorial review so that we were triggering the event under the wrong conditions. ;-)
> Fix Friends event

- EDDI/ChangeLog.md
- Events/CommanderContinuedEvent.cs
- Events/DiedEvent.cs
- ShipMonitor/ModuleArrivedEvent.cs
- ShipMonitor/ModulePurchasedEvent.cs
- ShipMonitor/ModuleRetrievedEvent.cs
- ShipMonitor/ModuleSoldEvent.cs
- ShipMonitor/ModuleSoldFromStorageEvent.cs
- ShipMonitor/ModuleStoredEvent.cs
- ShipMonitor/ModuleSwappedEvent.cs
- ShipMonitor/ModuleTransferEvent.cs
- ShipMonitor/ModulesStored.cs
- ShipMonitor/ShipArrivedEvent.cs
- ShipMonitor/ShipDeliveredEvent.cs
- ShipMonitor/ShipLoadoutEvent.cs
- ShipMonitor/ShipPurchasedEvent.cs
- ShipMonitor/ShipRenamedEvent.cs
- ShipMonitor/ShipSoldEvent.cs
- ShipMonitor/ShipSoldOnRebuyEvent.cs
- ShipMonitor/ShipSwappedEvent.cs
- ShipMonitor/ShipTransferInitiatedEvent.cs
- Tests/ShipTests.cs
Use ship definitions to convert from FDev ship names (e.g. `Empire_Eagle`) to human readable names players will readily recognize (e.g. `Imperial Eagle`).
Surprisingly, we don't seem to have internationalized ship models so there was less fixing than I though I'd need to do after internationalization was merged.
> Use human readable ship names in events

- EDDI/App.config
- EDDI/App.xaml.cs
- EDDI/EDDI.cs
- EDDI/EDDIConfiguration.cs
- EDDI/Properties/Settings.Designer.cs
- EDDI/Properties/Settings.settings
- Utilities/Logging.cs
- Utilities/Utilities.csproj
- Utilities/packages.config
- 2nd attempt to remove user directory information from Rollbar reports.
- Allow exceptions to pass through to Rollbar without a wrapper
- Standardize messages to report exceptions within the data payload (rather than sometimes within the message body)
- Revise Rollbar "Environment" variable to match EDDI version and "CodeVersion" variable match Git SHA. Per https://docs.rollbar.com/docs/source-control/ this will allow better linking between Rollbar and correct code versions for better stack traces.
- Move Rollbar initialization from EDDI.cs to App.xaml.cs and add hooks to improve EDDI's capture of unhandled exceptions.
- Catch and write managed exceptions (contained within try-catch statements) to the Visual Studios Output window while debugging.
> Rollbar enhancements

- DataDefinitions/Crime.cs
- DataDefinitions/Properties/Crimes.es.resx
- DataDefinitions/Properties/Crimes.fr.resx
- DataDefinitions/Properties/Crimes.resx
Notes:
- dockingMinorBlockingAirlock had a typo
- dockingMinorTresspass doesn't match the journal manual (has an extra `s`)
- dockingMajorTresspass doesn't match the journal manual (has an extra `s`)
- passengerWanted is a new crime that doesn't appear in the journal manual but is present in-game
> Update crime definitions per Rollbar data.

- DataDefinitions/Material.cs
- DataDefinitions/MaterialAmount.cs
- MaterialMonitor/MaterialMonitor.cs
- Tests/MaterialMonitorTests.cs
...and (now that everything is tracked by edname) simplify the material monitor. Remove all localized strings from materialmonitor.json. Also, update material monitor test.
> Remove dead code from the Material Monitor

- Utilities/Logging.cs
In light of the recent enhancements I proposed for Rollbar, we'll need to use the "environment" variable to check versioning information.
Also updated the reference link to match Rollbar's reorganized docs.
> Update Rollbar version checking

- DataDefinitions/StarSystem.cs
- DataDefinitions/SystemState.cs
- EDDPMonitor/SystemStateChangedEvent.cs
- Events/DockedEvent.cs
- Events/JumpedEvent.cs
With internationalization, the `state` string in the `StarSystem` class was converted to reference the `SystemState` object and was renamed to `systemState`.
This PR removes inconsistencies in handling different system states, resolves incompatibilities with existing Cottle scripts, and presents the system state to the end user as a localized string rather than as an object.
(converting the `EDDBID` in `StarSystem.cs` from `long` to `long?` is unrelated, though it did prevent some exceptions I was seeing while testing... possibly related to prior tests I've done with acquiring system data from EDSM, which doesn't provide an EDDBID)
> Fix system state info after internationalization

- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
- EDDI/Properties/EddiResources.Designer.cs
- EDDI/Properties/EddiResources.resx
Ref. #493. Allows an instance of EDDI to be initialized without starting start responders or monitors (including the journal parser).
This implementation is not quite the full extreme we discussed, as the visible config data can still be edited (I don't see a need to limit editing further at this time)
Resubmitting after rebasing.
> Implement "safe mode" for mandatory upgrades.

- CargoMonitor/Properties/CargoMonitor.es.resx
- CargoMonitor/Properties/CargoMonitor.fr.resx
- EDDI.sln
- EDDI/MainWindow.xaml.cs
- EDDI/Properties/EddiResources.Designer.cs
1. French and Spanish translations for "Needed" Cargo Monitor header (I've asked the chat in EDDI to confirm my tranlsations and they have)
2. Fixed some strings that were not converted to reference resx strings in Frontier API log in dialogs
> Fixup small translation errors and omissions

- Utilities/Logging.cs
Other errors trigger rollbar reports but rollbar seems to be at fault for slowing starts when this occurs by locking the applicable thread while it queries the Rollbar API and sends reports.
For all reports other than unhandled exceptions, this PR shifts rollbar API queries and reporting to an asynchronous tasks thread pool where they will be less disruptive.
> Mitigate Rollbar error reporting causing slow startup

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- Events/NearSurfaceEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/SpeechResponder.cs
- StatusMonitor/StatusMonitor.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
Ref. #417
Add a new top level `body` object, much like the current `station` object that is already present.
Modify the `Near surface` event to use body and system data and make available rich data about nearby bodies.
> `Near surface` event from journal `ApproachBody and `LeaveBody` events. Rich data about nearby bodies.

- Events/BodyScannedEvent.cs
- Events/StarScannedEvent.cs
> Resolve differences between `Body scanned` event properties and `BodyDetails()` properties.

- EDDI/ChangeLog.md
- StarMapService/StarMapService.cs
Ref. #566
1. When syncing more than a week of logs, EDSM would only return the first week. EDDI will now keep asking for logs until we have everything since our last sync date.
2.  When `since` has a value and we are doing a partial sync, we don't need to increment system visits. System visits are handled by the event handler for the `Jumped` event. We only need to write this value when doing a full sync.
> Fix EDSM Sync reset bug

- DataDefinitions/ModuleDefinitions.cs
When you buy a module, only one of SellItem or StoredItem is populated, depending whether you sell or store the existing module. Or both can be absent if you are filling an empty slot. 
ParseJournalEntry in JournalMonitor.cs line 1021 was not testing before passing the null string to Module.FromEDName(), but I think it is reasonable for Module.FromEDName() ro return null when passed a null input.
> If passed a null edName, return null

- EDDNResponder/EDDNResponder.cs
Going forward, we may want to assert an invariant that a CommodityQuote has a non-null CommodityDefinition.
> Catch null reference of CommodityQuote with null CommodityDefinition

- DataDefinitions/Material.cs
This material is "Rare" per right panel description but the in-game storage limits and material traders reveal that the material is really "Common".
> Fixed Zirconium rarity

- EDDI/EDDI.cs
Fix #614.
Don't forget the nearest stellar body when entering normal space near a station... the NearSurface event means that we have much better resolution on this then we used to and can handle these independently.
> Gracefully handle `CurrentStarSystem` being null.

- CargoMonitor/CargoMonitor.cs
- EDDI/ChangeLog.md
- Events/SearchAndRescueEvent.cs
- Tests/JournalMonitorTests.cs
There seems to be some inconsistency here between documentation and reality. The Cottle scripts expect `commodity` to be an object with properties `name` and `rare`. The docs and wiki say that `commodity is a string, being the localized name of the commodity.
I have restored the object behavior as it is more useful, but I'm uncertain what consequences this will have to Voice Attack, so I really need some VA users to test it please!
> #602 Fix SAR event commodity property

- VoiceAttackResponder/EddiVoiceAttackResponder.csproj
- VoiceAttackResponder/VoiceAttackPlugin.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
- Refactored to separate VoiceAttack plugin execution methods from VoiceAttack variable setting methods.
- Split background variable setting to a separate thread to prevent delays from the plugin in reacting to events.
- Revised the method for iterating object data and writing values to VoiceAttack. It now writes more properties than it did previously (auto-generated docs do not fully describe the currently written VoiceAttack variables that are generated for object data even though they *are* present).
This is a partial fix for #33. For a complete fix, we also need to auto-generate variable values in `GeneratorTests.cs` (I tried to implement this but was not able to do so successfully).
> Refactored, values updating split into distinct threads for events and bg values.

- EDDI/ChangeLog.md
- VoiceAttackResponder/VoiceAttackPlugin.cs
- VoiceAttackResponder/VoiceAttackResponder.cs
Trigger VoiceAttack variable updating via event handling rather than through continuously pushed loops. Fix for #720.
> Dramatically reduced CPU utilization in VoiceAtttack

- StatusMonitor/StatusMonitor.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
Fix for #747.
- VoiceAttackPlugin.cs
- values are set on the `VAInitialized` event - the prior `setValues` call was redundant.
- `setSpeaking` is set via an event - including it in the `setValues` method was redundant.
- VoiceAttackVariables.cs
- Created reference items so that we can track when an EDDI value has been modified
- Write new standard values only when the applicable item no longer matches the VoiceAttackPlugin's reference item.
Note: There is still a noticeable spike in CPU utilization when loading star systems - Many VoiceAttack variables are set when a new star system is loaded. Every commodity on every station and every material on every body is currently written to VoiceAttack, even though our documentation does not reflect this extensive reflection.
> Update VA standard variables only when they do not match prior state.

- EDDI/ChangeLog.md
- Events/EddiEvents.csproj
- Events/UnhandledEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/Personality.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
- VoiceAttackResponder/VoiceAttackResponder.cs
This will allow unknown events to be passed to monitors and responders even if we don't have a definition for that event yet.
To address issue #776.
Also corrects a null reference exception generated because EventArgs weren't being properly set.
> Create a generic event handler for unknown events.

- EDDI/EDDI.cs
> Fix CurrentStarSystem not matching destination system during `FSD engaged` event

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDSMResponder/EDSMResponder.cs
Exceptions could occur if the commander's name or API key was null and the starMapService consequently wasn't initialized.
> Fix null reference exceptions from edsm.json

- DataDefinitions/Module.cs
- EDDI/ChangeLog.md
- JournalMonitor/JournalMonitor.cs
Fix #769. ShipMonitor.json wasn't being serialized with full module objects. 
Add logic to identify compartment size from loadout events.
> Fix shipmonitor.json not recording full module object properties

- EDDI/EDDI.cs
It was only passing if the system contained bodies (planets, moons, etc.). A system with a station but no planets failed validation. Expanded validation to check for bodies, stations, or population. If any of the three are present, the system is valid.
Ref. #792
> Make system validation more flexible

- DataDefinitions/Status.cs
- EDDI/ChangeLog.md
FDev sets Status.hardpoints_deployed to true when you use the discovery scanner in supercruise. This has undesirable consequences, so we need to keep Status.hardpoints_deployed false while we are in supercruise.
Fixes #772
> Prevent Status.hardpoints_deployed being set to true in supercruise

- CargoMonitor/CargoMonitor.cs
- DataDefinitions/HaulageAmount.cs
- SpeechResponder/EddiSpeechResponder.csproj
- SpeechResponder/Help.md
- SpeechResponder/ScriptResolver.cs
- SpeechResponder/Variables.md
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.es.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
This PR addressed Issues #759 and #771.
1. There is a 'hole' the 'Commodity sold' event where it is difficult to determine whether a commodity sold in the black market is haulage or owned. Added check to classify as owned if commodity is prohibited.
Note: This will still be problematical if cmdr has not previously visited the station as EDDP data does not include prohibited commodities. Future change to phase out EDDP and use EliteBGS API will correct this.
2. 'Cargo Depot' (and, as a result, 'Mission completed') did not account for game mechanics change for solo 'source and return' missions implemented in 3.1. Now using haulage.amount to accurately track progress of the mission.
3. Added CargoDetails() and HaulageDetails() functions for Cottle scripting.
> Fix cargo tracking for 'Commodity sold' and 'Cargo depot' events

- EDDI/EDDI.cs
- EDDPMonitor/EddpMonitor.cs
- Events/JumpedEvent.cs
- Events/LocationEvent.cs
EDDP uses invariant economy names.
Fixes #804.
> Fix economy related exceptions.

- JournalMonitor/JournalMonitor.cs
The journal expects a marketID to always be present, even when not docked.
> Fix exception that occurs during location events if not docked

- CargoMonitor/CargoMonitor.cs
- DataDefinitions/Haulage.cs
- Tests/CargoMonitorTests.cs
Fixed 'Object reference not set to an instance of an object' exceptions reported by Rollbar, associated with the Cargo Monitor 'Cargo depot' and 'Mission abandoned' event handlers.
Added relevant unit testing in CargoMonitorTests.
> Fixed Cargo Monitor exceptions  from Rollbar

- SpeechService/SpeechService.cs
- Tests/SpeechTests.cs
Fix exception described by #821 & Rollbar data.
- Select voice using a Task rather than a thread (try-catch statements obtain exception info from a Task better than from another thread)
- Make sure that the configured voice is still valid prior to final selection.
- Implement an appropriate speech test for a null or invalid voice.
(Note that if synth.SelectVoice() is not called, the speech synthesizer will use the system default voice).
Resolves #821.
> Fix System.ArgumentException: Cannot set voice. No matching voice is installed or the voice was disabled

- EDDI/ChangeLog.md
- Events/BountyPaidEvent.cs
- Events/EddiEvents.csproj
- Events/FinePaidEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.es.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- Create new event `Bounty paid`, resolves #788 
- Update  `Fines paid` event per post-3.0 journal manual.
- Remove legacy fines properties and remove `PayLegacyFines` from the journal monitor - this event was deprecated with 3.0.
- Revise the retrieval of superpowers from the getFaction method so that it properly identifies and retrieves superpower names.
> Create a `Bounty paid` event and update the `Fine paid` event.

- DataDefinitions/Mission.cs
- MissionMonitor/MissionMonitor.cs
Fix for 'Mission warning' event to properly trigger at start of session.
> 'Mission warning' event hotfix

- CargoMonitor/CargoMonitor.cs
- DataDefinitions/Haulage.cs
- ShipMonitor/ShipMonitor.cs
Corrects:
- multiple 'Cargo update' triggers (Issue #873).
- Haulage object private 'sets', resulting in null values
- Typo in Cargo Depot 'delivery' update code.
> Cargo Monitor hotfixes

- DataDefinitions/Module.cs
- DataDefinitions/ResourceBasedLocalizedEDName.cs
- DataDefinitions/Ship.cs
- JournalMonitor/JournalMonitor.cs
- Tests/JournalMonitorTests.cs
- Tests/ShipTests.cs
The previous approach of setting the JsonProperty attribute on edname and basename was causing trouble because rather than create new objects, Json.NET would simply mutate those properties on an existing object. This would cause problems if the object was in the `AllOfThem` list or otherwise shared.
This new custom JsonConverter instead reads the edname from the JObject and uses it to call FromEDName().
> Implement a JsonConverter that uses FromEDName()

- EDDI/ChangeLog.md
- VoiceAttackResponder/EDDI.vap
- VoiceAttackResponder/VoiceAttackPlugin.cs
Write uri's for EDDB, EDShipyard, and EDSM to VA variable `{TXT:EDDI uri}` when the appropriate plugin command is invoked.
Permit an optional boolean to be set which suppresses opening the browser from the uri.
Add an `edshipyard` command callable from the plugin, like for `coriolis`.
Update applicable commands in EDDI.vap.
NOTE: EDShipyard does not currently accept `loadout` raw data, so `edshipyard` is of limited value. Included for completeness.
Resolves #888.
> Make uri's accessible to VA users

- EDDI/ChangeLog.md
- ShipMonitor/ShipFsdEvent.cs
- StatusMonitor/StatusMonitor.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
- `charging complete` now triggers at a more appropriate time.
- Added new FSD status - `charging canceled`.
Fixes #886.
> Revised ship FSD charging status

- JournalMonitor/JournalMonitor.cs
Fix log entries like `2018-10-27T23:07:51 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name paint in resource EddiDataDefinitions.Properties.Modules`
> Don't try to find a "Paint" module when performing repairs.

- EDDI/App.xaml.cs
- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
> Increment logs only once per EDDI instance, being sensitive as to whether we are starting from VA.

- JournalMonitor/JournalMonitor.cs
- Tests/JournalMonitorTests.cs
> Suppress an unnecessary `Message received` event when entering a new system and connecting to a new system-wide chat channel.

- VoiceAttackResponder/VoiceAttackPlugin.cs
> Fix `coriolis`, `edshipyard`, `eddbsystem`, and `eddbstation` commands not invoked correctly from VoiceAttack

- SpeechService/SpeechService.cs
For exceptions like:
```
2018-11-04T19:09:04 [Warning] SpeechService:speak Failed to select voice IVONA 2 Amy OEM System.InvalidOperationException: A task may only be disposed if it is in a completion state (RanToCompletion, Faulted or Canceled).
at System.Threading.Tasks.Task.Dispose(Boolean disposing)
at System.Threading.Tasks.Task.Dispose()
at EddiSpeechService.SpeechService.<>c__DisplayClass25_0.<speak>b__0() in EDDI\SpeechService\SpeechService.cs:line 395
```
(most likely to be seen by developers rather than end users)
> Fix SpeechService timeout exception

- VoiceAttackResponder/VoiceAttackVariables.cs
```
2018-11-08T06:51:07 [Error] VoiceAttackVariables:setStandardValues Failed to set last station Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The best overloaded method match for 'VoiceAttack.VoiceAttackInitProxyClass.SetText(string, string)' has some invalid arguments
at CallSite.Target(Closure , CallSite , Object , String , FactionState )
at EddiVoiceAttackResponder.VoiceAttackVariables.setStationValues(Station station, String prefix, Object& vaProxy) in EDDI\VoiceAttackResponder\VoiceAttackVariables.cs:line 494
at EddiVoiceAttackResponder.VoiceAttackVariables.setStandardValues(Object& vaProxy) in EDDI\VoiceAttackResponder\VoiceAttackVariables.cs:line 283
```
> Fix  null reference exception when current station is not set

- Events/BeltScannedEvent.cs
- Events/BodyScannedEvent.cs
- Events/StarScannedEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/SpeechResponder.cs
Implements the `scantype` property from the `Scan` event.
Use it to distinguish and suppress extra nav beacon scans.
Use it to determine whether scans are detailed or not for estimating scan values.
Note: Nav beacon scanning is a result of [this FDev bug](https://forums.frontier.co.uk/showthread.php/455841-NavBeaconScan-writes-two-entries-per-body-to-journal?highlight=scantype).
> Prevent nav beacon scan spamming in chapter 4 beta (compatible w/ chapter 3)

- EDDNResponder/EDDNResponder.cs
- JournalMonitor/JournalMonitor.cs
- Tests/EddnTests.cs
- Tests/JournalMonitorTests.cs
Fix #941 by ensuring that the EDDN responder is not affected by any failure to parse event details.
Instead, the EDDN responder will parse from raw event data. 
Advantages of this approach:
- Changes to the journal monitor's parsing of event details is less likely to disrupt / cause missing messages for the EDDN responder
- More events are taken into account when tracking location data (especially market ID)
- More complete data is sent to EDDN
> EDDN responder restructured to use journal event raws

- StarMapService/EdsmStationData.cs
When parsing a station without a "controllingFaction" key.
> EDSM station data: Fix null reference exception from missing faction info

- EDDI/Properties/MainWindow.Designer.cs
- EDDI/Properties/MainWindow.resx
Note: It looks like CrowdIn supports a version control feature that we may be able to use to hook Crowdin to this branch to request re-translation?
> Clarify that verbose logs are only placed on the desktop when the `Report an Issue` button is clicked.

- DataDefinitions/Properties/StationModels.Designer.cs
- DataDefinitions/Properties/StationModels.resx
- EDDI/ChangeLog.md
- SpeechResponder/ScriptResolver.cs
- SpeechService/Translations.cs
- Tests/EdsmDataTests.cs
- Tests/TranslationTests.cs
Invariant names may be used by end user scripts. And are often used to parse EDSM data.
This PR implements the same fix as a pronunciation fix-up accessible via the `P()` function while restoring the original invariant name.
> Convert station model pronunciation fixups to use `P()` function, rather than editing the invariant name.

- JournalMonitor/JournalMonitor.cs
> Fix Blueprint Names in `EngineerCraft` event

- DataDefinitions/Properties/StationModels.de.resx
- DataDefinitions/Properties/StationModels.es.resx
- DataDefinitions/Properties/StationModels.fr.resx
- DataDefinitions/Properties/StationModels.it.resx
According to our change history, the prior translations were discarded on the same day that 3.1.1 was released. Perhaps CrowdIn dumped the translations once the neutral language text changed?
Restores station model translations and fixes #981.
> Restore station model translations and fix #981.

- EDDI/ChangeLog.md
- SpeechResponder/EddiSpeechResponder.csproj
- SpeechResponder/Help.md
- SpeechResponder/ScriptResolver.cs
- SpeechResponder/Variables.md
- SpeechService/SpeechService.cs
To permit examining voice details (like voice culture and gender) while scripting, primarily for use with the `Voice()` function.
> Add a new `VoiceDetails` function to Cottle

- DataDefinitions/ShipDefinitions.cs
- EDDI/MainWindow.xaml.cs
- EDDPMonitor/ConfigurationWindow.xaml.cs
Went thru each dropdown menu in the UI and took a decision on how it should be sorted, commenting where necessary.
There the menu has a "None" option I left it at the top.
I did not sort squadron ranks as they are (or should be) enumerated in order of seniority.
Sorted the ship names and removed the speculative entries.
Fixes #961
> Sort dropdown menus appropriately

- EDDI/ChangeLog.md
- EDDNResponder/EDDNResponder.cs
- Tests/EddnTests.cs
- The `FSDTarget` event needs to be ignored by the EDDN responder.
- Fixed a bug that was causing missing location data from events to revert our global location variables to null and not to maintain the prior state
- Added heuristics for confirming body scans based on body and system names (these heuristics will be helpful much of the time, but they will not be as helpful with named bodies and named systems).
- Added a `sendToEddn` boolean to ensure test methods don't send data to EDDN inadvertently, even on release builds.
> EDDN responder updates

- EDDI/ChangeLog.md
- EDDNResponder/EDDNResponder.cs
- EDDNResponder/EddiEddnResponder.csproj
- EDDNResponder/Properties/EddnResources.Designer.cs
- EDDNResponder/Properties/EddnResources.resx
- Tests/EddnTests.cs
Refactored.
The EDDN responder will now provide an audible warning if it detects that location data is in an invalid state.
Revised tests.
> Revisions to prevent inaccurate star position data being reported to EDDN 

- DataProviderService/DataProviderService.cs
- EDDI/EDDI.cs
Make sure that system metadata is populated for each body looked up from the server or scanned.
> Fix body system metadata sometimes being not set.

- GalnetMonitor/Properties/GalnetMonitor.Designer.cs
- GalnetMonitor/Properties/GalnetMonitor.resx
Ref. #1090
Recommendation: Restore translated language regex filters after incorporation.
> Incorporate Galnet regex tweak

- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
Fix #1109 by requiring at least 3 characters before attempting to lookup star systems.
> Fix EDDI hanging when trying to input home system

- EDSMResponder/EDSMResponder.cs
(was failing when trying to cast unhandled events).
Fixes errors like:
```
2019-01-23T10:52:16 [Warning] EDDI:OnEvent Responder failed System.InvalidCastException: Unable to cast object of type 'EddiEvents.UnhandledEvent' to type 'EddiShipMonitor.ShipLoadoutEvent'.
at EddiEdsmResponder.EDSMResponder.prepareEventData(Event theEvent)
at EddiEdsmResponder.EDSMResponder.Handle(Event theEvent)
at Eddi.EDDI.<>c__DisplayClass118_1.b__0()
```
Reference #1106.
> Fix invalid cast exceptions in the EDSM responder

- ShipMonitor/ModulePurchasedEvent.cs
- ShipMonitor/ModuleRetrievedEvent.cs
- ShipMonitor/ModuleSoldEvent.cs
- ShipMonitor/ModuleStoredEvent.cs
- ShipMonitor/ModulesStored.cs
- ShipMonitor/ShipMonitor.cs
- Tests/ShipTests.cs
- Fixes #1106
- If the shipyard does not contain a ship with a local id matching the event, create a basic ship from the module event to receive the event data, pulling in ship definitions (like military compartment sizes).
- Revise `AddModule` and `RemoveModule` events to ensure any exception results in no change to the shipyard.
- Add an appropriate test.
Fixes issues like https://rollbar.com/EDCD/EDDI/items/11363/occurrences/64537533570/
```
{"ship":"Federal Corvette","shipid":119,"slot":"Military01","buymodule":{"edname":"Int_GuardianShieldReinforcement_Size5_Class2","class":5,"grade":"D","value":995328,"ShipId":null,"mount":null,"clipcapacity":null,"hoppercapacity":null,"ammoinclip":null,"ammoinhopper":null,"price":873402,"enabled":true,"priority":1,"position":0,"power":0.0,"health":1 …
```
> Improve handling of module events when shipyard contains minimal or no ship definition.

- DataProviderService/StarSystemSqLiteRepository.cs
- EDDI/EDDI.cs
Fix #1143.
We need to consider all system sources, not just fetched systems, before adding a new star system to the database.
> Fix system visit counts reseting

- CargoMonitor/CargoMonitor.cs
- CargoMonitor/CargoMonitorConfiguration.cs
- MissionMonitor/MissionMonitor.cs
- MissionMonitor/MissionMonitorConfiguration.cs
- Tests/CargoMonitorTests.cs
- Tests/MissionMonitorTests.cs
* Added protection against mission and haulage entries being duplicated during EDDI 'Log Load' startup.
* Improved 'Log Load' parsing efficiency for mission and haulage related events by skipping those already updated in respective monitor json files.
> Protection from mission & haulage duplicates

- Events/JumpedEvent.cs
- JournalMonitor/JournalMonitor.cs
- MissionMonitor/MissionMonitor.cs
- SpeechResponder/ScriptResolver.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
* Added ability to set route to individual systems in Cottle `RouteDetails()` and VA external plugin function, `missionsroute`.
* Added ability to cancel route(s) in Cottle `RouteDetails()` and VA external plugin function, `missionsroute`.
* Added ``destination` and `destdistance` properties to the `Jumped` event to allow tracking of progress to route destination.
> Add 'set' & 'cancel' to route plotting functions

- ShipMonitor/ShipMonitor.cs
Simple fix to not remove current ship from the Shipyard in the ShipMonitor `StoredShips` event handler.
> Do not remove current ship in `StoredShips` event handler

- EDDI/EDDI.cs
- EDSMResponder/ConfigurationWindow.xaml.cs
- EDSMResponder/EDSMResponder.cs
- StarMapService/StarMapService.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
Prevents issues like `2019-02-08T22:17:23 [Warning] StarMapService:sendEvent EDSM responded with Missing commander name` by verifying that StarMapService.Instance can only be initialized with credentials and is not null prior to attempting to send data, and by managing access through a single instance.
Ref. https://forums.frontier.co.uk/showthread.php/387955-EDDI-3-3-Bring-your-cockpit-to-life?p=7410330&viewfull=1#post7410330
> Tighten up EDSM credentials management

- CargoMonitor/CargoMonitor.cs
- CargoMonitor/ConfigurationWindow.xaml.cs
- EDDI/EDDI.cs
- EDDPMonitor/EddpMonitor.cs
- GalnetMonitor/ConfigurationWindow.xaml.cs
- GalnetMonitor/GalnetMonitor.cs
- JournalMonitor/JournalMonitor.cs
- MaterialMonitor/ConfigurationWindow.xaml.cs
- MaterialMonitor/MaterialMonitor.cs
- MissionMonitor/ConfigurationWindow.xaml.cs
- MissionMonitor/MissionMonitor.cs
- ShipMonitor/ConfigurationWindow.xaml.cs
- ShipMonitor/ShipMonitor.cs
- SpeechResponder/ConfigurationWindow.xaml.cs
- SpeechResponder/EditScriptWindow.xaml.cs
- SpeechResponder/ScriptResolver.cs
- SpeechResponder/SpeechResponder.cs
- SpeechService/SpeechService.cs
- StatusMonitor/StatusMonitor.cs
- Tests/StatusMonitorTests.cs
- VoiceAttackResponder/EDDI.vap
- VoiceAttackResponder/VoiceAttackPlugin.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
Removes `Instance` properties from monitors (I found that these were not generating true singletons, and consequently were not achieving their end purpose).
Scales back event handling of VA variables no non-nullable types only exceptions were being generated from trying to subscribe to null objects).
> Fix VA variables (partially reverts PR #1172)

- EDDI/EDDI.cs
Removed legacy `dummyRefreshMarketData()` call when cAPI is down.
* The station data for EDDN is NOT accurate
* The module swap savings report is confusing
> Do not update market data when cAPI is down.

- EDDI/ChangeLog.md
- ShipMonitor/ConfigurationWindow.xaml.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
- VoiceAttackResponder/VoiceAttackResponder.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
- docs/VoiceAttack-Integration.md
Revises the VoiceAttack event handler to mimic the way events are handled in EDDI.cs.
Fixes #1155 - Significant performance improvement.
Fixes #1182 - a ship monitor lock up that can occur when opening the ship monitor from VA.
I also noticed significant delays from writing shipyard data. These changes minimize those delays by setting VA shipyard variables in the background and only for ships that have been changed.
> VoiceAttack event handling reworked to minimize delays

- CompanionAppService/CompanionAppService.cs
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
- Events/Event.cs
- ShipMonitor/ConfigurationWindow.xaml.cs
- SpeechResponder/ConfigurationWindow.xaml
- SpeechResponder/ConfigurationWindow.xaml.cs
- SpeechResponder/EddiSpeechResponder.csproj
- SpeechResponder/EditScriptWindow.xaml.cs
- SpeechResponder/MarkdownWindow.xaml
- SpeechResponder/MarkdownWindow.xaml.cs
- SpeechResponder/Properties/SpeechResponder.Designer.cs
- SpeechResponder/Properties/SpeechResponder.de.resx
- SpeechResponder/Properties/SpeechResponder.es.resx
- SpeechResponder/Properties/SpeechResponder.fr.resx
- SpeechResponder/Properties/SpeechResponder.hu.resx
- SpeechResponder/Properties/SpeechResponder.ja.resx
- SpeechResponder/Properties/SpeechResponder.resx
- SpeechResponder/Script.cs
- SpeechResponder/SpeechResponder.cs
- SpeechResponder/SpeechResponderHelp.md
- SpeechService/EddiSpeech.cs
- SpeechService/EddiSpeechService.csproj
- SpeechService/SpeechService.cs
- Tests/SpeechUnitTests.cs
- Tests/Tests.csproj
- VoiceAttackResponder/VoiceAttackPlugin.cs
- docs/VoiceAttack-Integration.md
Resolved #1192 and de-couples the speech responder so that it shall longer bottlenecks event processing. Adds the ability to prioritize speech, with priority 1 speech being spoken before priority 2, 2 before 3, etc. Additionally, priority 1 speech will interrupt lower priority speech and priority 5 speech is interruptible by any higher priority speech.
> Speech responder priorities

- DataDefinitions/ModuleDefinitions.cs
Fix erroneous edname being reported to EDDN via CAPI (using lookup up via EliteID via the ModuleDefinitions.cs `FromEliteId` method).
> Fix erroneous edname being reported to EDDN

- VoiceAttackResponder/Properties/VoiceAttack.Designer.cs
- VoiceAttackResponder/Properties/VoiceAttack.resx
Note: The Brazilian translation already references correct information and should be preserved in / restored after this merging.
> Correct VoiceAttack description text to match VoiceAttack's redesigned UI

- ShipMonitor/ShipMonitor.cs
- Tests/BodyScanTests.cs
- Tests/CargoMonitorTests.cs
- Tests/CommanderDataTests.cs
- Tests/CommodityTests.cs
- Tests/CoriolisTests.cs
- Tests/DataDefinitionTests.cs
- Tests/DataProviderTests.cs
- Tests/DiffTests.cs
- Tests/EddiCoreTests.cs
- Tests/EddnTests.cs
- Tests/EdsmDataTests.cs
- Tests/JournalMonitorTests.cs
- Tests/MaterialMonitorTests.cs
- Tests/MissionMonitorTests.cs
- Tests/PromotionTests.cs
- Tests/ScriptResolverTest.cs
- Tests/ShipTests.cs
- Tests/SpeechTests.cs
- Tests/StatusMonitorTests.cs
- Tests/TestBase.cs
- Tests/Tests.csproj
- Tests/TranslationTests.cs
- Tests/VersioningTests.cs
- Tests/VoiceAttackPluginTests.cs
- Utilities/Files.cs
Works for all methods where tests files are written via the `Files.Write` method in `Utilities.cs` and where the test initializer sets the `Files.cs` static bool to true.
> Prevent unit tests from writing to permanent storage

- CompanionAppService/CompanionAppService.cs
- Tests/Abasheli Barracks.json
- Tests/CapiShipyardTests.cs
- Tests/Tests.csproj
It boils down to "shipyard_list" being an object of objects, while ""unavailable_list" is an array of objects.
Thanks, FDev.
> Amend #1207 with tests

- DataProviderService/StarSystemRepository.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- StarMapService/EdsmSystemData.cs
- Tests/EddnTests.cs
- Tests/EdsmDataTests.cs
- Fixed EDSM Sphere and Cube systems queries. Added unit tests.
- Added `refreshIfOutdated` option (defaulted to `True`) to `GetOrCreateStarSystems` and `GetOrFetchStarSystems` to minimize EDSM system(s) queries when only static data is required.
> Fixed EDSM sphere & cube queries

- EDDI/StarSystemComboBox.cs
Do not query EDSM with 'partial' < 2 chars
> System Selection Tweak

- EDDI/ChangeLog.md
- JournalMonitor/LogMonitor.cs
Fixes missing events when we load a new session of Elite Dangerous with EDDI already running.
Resolves #1233.
> Fix missing fileheader events

- EDDNResponder/EDDNResponder.cs
- Tests/EddnTests.cs
Fixes #1275 
Corrects "_Localised" properties not being stripped correctly (causing "Jumped" messages to be rejected as invalid). 
Strips latitude and longitude.
Improves error reporting for invalid messages submitted to EDDN.
> Correct invalid EDDN messages

- SpeechService/SpeechFX.cs
A small adjustment to better equalize volume gain across chorus levels (chorus level zero was quieter than other levels where a chorus effect was applied).
> Slightly boost speech volume when chorus level is low.

- CompanionAppService/CompanionAppService.cs
- DataDefinitions/Module.cs
- DataDefinitions/ModuleDefinitions.cs
- ShipMonitor/ShipMonitor.cs
- Tests/ShipTests.cs
- Add EDDBIDs to newer module definitions
- Add missing modules from https://github.com/EDCD/FDevIDs/pull/33/files
- Improve reporting of missing module definitions
- Refactor and harden ShipMonitor.cs against exceptions like "An item with the same key has already been added." Ref. https://rollbar.com/EDCD/EDDI/items/15048/
- Enhance `Module swapped` unit testing.
- Implement suggestions from code analysis.
> Update module definitions and resolve `Module swapped` exception

- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
- Attach logs from both the current session and last session (since people sometimes report issues that occurred on the prior run but not the current run)
- Include the VoiceAttack version, when appropriate.
> Update attachable logs for Github issues

- GalnetMonitor/GalnetMonitor.cs
```
2019-05-01T02:10:59 [Error] GalnetMonitor:monitor Exception attempting to handle galnet feed:  {"ClassName":"System.ArgumentNullException","Message":"Value cannot be null.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Text.RegularExpressions.Regex.IsMatch(String input)\r\n   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)\r\n   at GalnetMonitor.GalnetMonitor.assignCategory(String title, String content) in C:\\Users\\%USERNAME%\\source\\repos\\EDDI\\GalnetMonitor\\GalnetMonitor.cs:line 286\r\n   at GalnetMonitor.GalnetMonitor.<monitor>g__monitorGalnet|20_0() in C:\\Users\\%USERNAME%\\source\\repos\\EDDI\\GalnetMonitor\\GalnetMonitor.cs:line 206","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nIsM …
```
> Fix exception generated when Galnet feed item content is null.

- StarMapService/EdsmBodyData.cs
- StarMapService/EdsmFactionData.cs
- StarMapService/EdsmStationData.cs
- StarMapService/EdsmSystemData.cs
- StarMapService/EdsmTrafficData.cs
- Tests/EdsmDataTests.cs
Fix deep-space crash when searching cube systems and EDSM results are an empty json / not the expected json type. 
Fixes #1316
> Fix deep-space crash caused by empty EDSM array

- Installer.iss
Fix #1322 by removing incompatible .dll files (like .dll files from future versions) during the installation process.
Only files prefixed "Eddi" and ending in ".dll" are affected (e.g. EddiCrimeMonitor.dll).
> Clear old / incompatible .dll files before installing

- EDDNResponder/EDDNEconomy.cs
Error message from EDDN:
```
"Response": "FAIL: [<ValidationError: " Additional properties are not allowed(u 'Proportion', u 'Name', u 'Name_Localized' were unexpected)">]",
"Exception": {
"ClassName": "System.ArgumentException",
"Message": "Value does not fall within the expected range.",
"Data": null,
"InnerException": null,
"HelpURL": null,
"StackTraceString": "   at EDDNResponder.EDDNResponder.<>c__DisplayClass59_0.<sendMessage>b__0() in C:\\Users\\%USERNAME%\\source\\repos\\EDDI\\EDDNResponder\\EDDNResponder.cs:line 558",
"RemoteStackTraceString": null,
"RemoteStackIndex": 0,
"ExceptionMethod": "8\n<sendMessage>b__0\nEddiEddnResponder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\nEDDNResponder.EDDNResponder+<>c__DisplayClass59_0\nVoid <sendMessage>b__0()",
"HResult": …
```
> Fix EDDN commodies message exception due to EDDNEconomy definition.

- BgsService/BgsFactionData.cs
Example from log:
```json
{
"system_name": "Eol Prou LW-L c8-48",
"system_name_lower": "eol prou lw-l c8-48",
"state": "none",
"influence": 0.046,
"recovering_states": [],
"pending_states": [{
"state": "boom",
"trend": 1
}
],
"active_states": []
}
```
> Fix exception that can occur when `happiness` or `updated_at` properties are not provided for faction BGS data

- DataDefinitions/Ship.cs
- EDDNResponder/EDDNResponder.cs
- ShipMonitor/ShipLoadoutEvent.cs
- ShipMonitor/ShipMonitor.cs
- Tests/ShipTests.cs
- Utilities/JsonParsing.cs
Ship deserialization wasn't deserializing ednames.
```
2019-06-06T21:35:20 [Error] EDDNResponder:sendMessage Failed to send data to EDDN {"eddnMessage":"{\"timestamp\":\"2019-06-06T21:35:20Z\",\"systemName\":\"Aryak\",\"stationName\":\"Garneau Port\",\"marketId\":3230837248,\"ships\":[null,null,null,null,null,null,null,null,null,null],\"horizons\":true}","Response":"FAIL: [<ValidationError: '[None, None, None, None, None, None, None, None, None, None] has non-unique elements'>]","Exception":{"ClassName":"System.ArgumentException","Message":"Value does not fall within the expected range.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at EDDNResponder.EDDNResponder.<>c__DisplayClass59_0.<sendMessage>b__0()","RemoteStackTraceString":null,"RemoteStackIndex":0,"Excepti …
```
> Fix EDDN exception - shipyard information

- ShipMonitor/ShipMonitor.cs
2019-06-16T23:14:20 [Error] ShipMonitor:sortCompartments Failed to sort ship compartments {"Exception":{"ClassName":"System.ArgumentException","Message":"An item with the same key has already been added.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)\r\n   at EddiShipMonitor.ShipMonitor.sortCompartments(Ship ship) in C:\\Users\\%USERNAME%\\source\\repos\\EDDI\\ShipMonitor\\ShipMonitor.cs:line 1412","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nThrowArgumentException\nmscorlib, Version=4.0.0.0, …
> Fix exception when sorting modules after module purchase

- DataProviderService/DataProviderService.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- EDDI/ChangeLog.md
- EDSMResponder/ConfigurationWindow.xaml.cs
- JournalMonitor/JournalMonitor.cs
- StarMapService/StarMapService.cs
- Without looping on the star system, the same star system could be added to our list of star systems multiple times (causing it to be added to the database multiple times).
- Create empty star systems to log visits for stars not in the database rather than trying to pull full data on each star system. (StarSystems will be fleshed out via visits or SystemDetails() and similar).
- Optimizes comments sync to only fetch comments once.
- Adds `systemaddress` and `edsmid` unique columns and prefer searching for these values using new indices.
- Optimizes database access to take full advantage of indexing with binary search.
- Sets up basic versioning for future table updates.
Fixes #1343 and significantly boosts synchronization speeds.
Bonus: Fix ship and module arrived events triggering from …
> Refactor `syncEdsmLogBatch` to loop through star systems before looping through flight logs, optimize database access

- DataDefinitions/Power.cs
Background: `Ship targeted` event `faction` property can be either a minor faction or power. The Crime Monitor event handler uses both `DataProviderService.GetFactionByName()` and `Power.FromEDName()` to determine which.
Fix serves to screen the ResourceBasedLocalizedEDName [Info] reports when the `@event.faction` property is a minor faction.
> Fix to screen unknown 'Power' ednames

- BgsService/BgsFactionData.cs
- EDDI/ChangeLog.md
Fir errors like
```
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n
at System.Threading.Tasks.Task`1.get_Result()\r\n
at EddiBgsService.BgsService.ParseFactionsAsync(List`1 responses)\r\n
at EddiBgsService.BgsService.GetFactions(String endpoint, List`1 queryList)\r\n
at EddiDataProviderService.DataProviderService.GetFactionByName(String factionName, String systemName)\r\n
at EddiCrimeMonitor.CrimeMonitor.handleShipTargetedEvent(ShipTargetedEvent event)\r\n
at EddiCrimeMonitor.CrimeMonitor.PreHandle(Event event)\r\n
at Eddi.EDDI.passToMonitorPreHandlers(Event event)
```
which can occur when a faction's influence is 100% as in the example below:
```json
{ …
```
> Fix BGS Faction invalid cast exception

- EDDI/ChangeLog.md
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- SpeechResponder/eddi.ru.json
> Update `Docking granted` script to include basic landing pad info for surface ports.

- .codecov.yml
- Tests/packages.config
- appveyor.yml
Resolves #1406.
Converts the script used to generate code coverage to a powershell script that can be run locally from the EDDI repos folder to generate code coverage reports locally.
At least in theory, code coverage must now drop by more than 10% for CodeCov to fail the build.
> Code coverage fixes

- appveyor.yml
- Include tests from the UnitTests namespace in the coverage evaluation.
- Exclude *.xaml (but not *.xaml.*) from code coverage.
> Code coverage tweaks

- JournalMonitor/JournalMonitor.cs
- Tests/ShipTests.cs
> Remove rounding from the "full" bool in the `Ship refuelled` event.

- CrimeMonitor/CrimeMonitor.cs
- DataDefinitions/Properties/StationLargestPad.Designer.cs
- DataDefinitions/Ship.cs
- DataDefinitions/Station.cs
- DataDefinitions/StationLargestPad.cs
- NavigationService/Navigation.cs
- ShipMonitor/ShipMonitor.cs
- SpeechService/SpeechFX.cs
- Tests/TestBase.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
Note: Please review #1424 prior to reviewing this PR.
The method isn't really serving any useful purpose, streamline to simply use ednames instead.
Removes an area with inconsistently reported code coverage (possibly because abbreviated values if if conditions were being hit while enum values were not).
> Remove the StationLargestPad `FromSize` method.

- CompanionAppService/CompanionAppService.cs
- CompanionAppService/Profile.cs
- EDDI/EDDI.cs
- EDDI/MarketInfoReader.cs
- EDDI/OutfittingInfoReader.cs
- EDDI/ShipyardInfoReader.cs
- EDDNResponder/EDDNResponder.cs
- Events/MarketInformationUpdatedEvent.cs
Add sanity checks for updates from `market.json`, `outfitting.json`, and `shipyard.json`.
Add `docked` and `alive` properties from the Frontier API profile.
Convert the `MarketInformationUpdated` event to be more self contained.
> EDDN sanity checks

- SpeechResponder/ConfigurationWindow.xaml.cs
The "Read about the speech responder's functions here" hyperlink was broken by recent changes. Since the click is triggered by a hyperlink, the sender is never a checkbox and does not trigger on loading the UI.
> Fix inadvertantly disabled hyperlink in the Speech Responder tab

- SpeechResponder/ConfigurationWindow.xaml
- SpeechResponder/ConfigurationWindow.xaml.cs
- SpeechResponder/EditScriptWindow.xaml
- SpeechResponder/EditScriptWindow.xaml.cs
- SpeechResponder/Personality.cs
- SpeechResponder/Properties/SpeechResponder.Designer.cs
- SpeechResponder/Properties/SpeechResponder.resx
- SpeechResponder/Script.cs
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.es.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- SpeechResponder/eddi.pt-BR.json
- SpeechResponder/eddi.ru.json
Resolves #1464.
Replaces #1469 and #1475.
If either `Delete` or `Reset` is enabled then the script is non-default.
Stores the default script when we're loading scripts and automatically determines whether a script matches the default.
Adds a confirmation dialog prior to resetting a script from the main window tab.
> Revise the `Delete` button in the Speech Responder UI to either `Delete` or `Reset`, as appropriate.

- SpeechService/Translations.cs
Rather than "Luyten two hundred and five to one hundred and twenty eight".
Ref. https://forums.frontier.co.uk/threads/eddi-3-3-bring-your-cockpit-to-life.387955/post-8002482
> Correct pronunciation of "Luyten 205-128" to speak the dash

- DataDefinitions/StarSystem.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- EDDI/EDDI.cs
Resolves #1480.
Uses data that we were already deserializing to carry over data not available from the server when we refresh stale star system data from the server.
> Preserve exploration results through server updates

- EDDI/EDDI.cs
- EDDI/EDDIConfiguration.cs
The `Powerplay` event was intended to trigger once but powermerits were being reset whenever the Frontier API updated the Cmdr object. This PR corrects the repetition by saving power merits to EddiConfiguration.
> Fix repeating powerplay event

- SpeechService/Translations.cs
- Tests/TranslationTests.cs
Prevents "A" in "Oopailks NV-X c17-1 AB 6 A Ring" from being pronounced as "Oopailks NV-X c17-1 AB 6 __ah__ Ring".
Prevents one "A" from being dropped in "Pru Aescs NC-M d7-192 A A Belt" and prevents pronunciation like "Pru Aescs NC-M d7-192 __ah__ Belt"
> Correct pronunciation of rings and belts

- SpeechResponder/Variables.md
- StatusMonitor/Status.cs
- StatusMonitor/StatusMonitor.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
- docs/VoiceAttack-Integration.md
Incorporating @Hoodathunk 's shiny new slope calculations.
Why is this necessary? Glide can occur at altitudes > 25 km. The old algorithm discarded possible glide signals above this altitude. 
- glide events were documented as only occurring under 25 km altitude and 
- the under 25 km was born out by prior testing. 
Since the 3.5 update, glide has been observed to occur at altitudes as high as 60 km.
Slope has been added to the algorithm to make sure that we do not confuse gliding into a planet and crashing into the planet.
> Re-reinstate glide

- Events/BodyScannedEvent.cs
- Events/StarScannedEvent.cs
Resolution to Issue #1525.
* Make `scantype` user-facing to to support filtering of scan types in body and star reports.
* Add `scoopable` to `Star scanned` event.
> Make body & star scanned 'scantype` property user-facing

- ShipMonitor/ShipMonitor.cs
Fixes exceptions like:
```
Object reference not set to an instance of an object.
at EddiShipMonitor.ShipMonitor.<>c.<MaxFuelPerJump>b__85_0(Compartment c)
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at EddiShipMonitor.ShipMonitor.MaxFuelPerJump(Ship ship)
at EddiShipMonitor.ShipMonitor.ParseShipLoadoutEvent(ShipLoadoutEvent event)
at EddiShipMonitor.ShipMonitor.handleShipLoadoutEvent(ShipLoadoutEvent event)
at EddiShipMonitor.ShipMonitor.PreHandle(Event event)
at Eddi.EDDI.passToMonitorPreHandlers(Event event)
```
https://rollbar.com/EDCD/EDDI/items/16004/?item_page=0&#instances
> Fix a possible null reference exception with the `MaxFuelPerJump` method

- DataDefinitions/CommodityDefinition.cs
- EDDI/MainWindow.xaml.cs
Fixes (or attempts to fix) exceptions like logged here:
https://rollbar.com/EDCD/EDDI/items/16001/
The fix for InvalidOperationsException is speculative - I experimented in both standalone and in VoiceAttack but I have not discovered the precise conditions necessary to trigger that exception.
The two error messages targeted by this PR are ~ 98.6% of all logged `Exception obtaining profile` exceptions (some of the most common exceptions reported to Rollbar).
> Fix `Exception obtaining profile` errors

- DataDefinitions/Mission.cs
- DataDefinitions/StarSystem.cs
- EDDI/EDDI.cs
- EDDI/MarketInfoReader.cs
- EDDI/OutfittingInfoReader.cs
- EDDI/ShipyardInfoReader.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/ScriptResolver.cs
- StarMapService/EdsmBodyData.cs
- StarMapService/EdsmFactionData.cs
- StatusMonitor/StatusMonitor.cs
- Utilities/JsonParsing.cs
Resolves #1571
Replaces #1572 
- Centralizes DateTime parsing to a new `getDateTime` method in Utilities.cs
- Centralizes conversion from DateTime to epoch seconds to the already existing `fromDateTimeToSeconds` method in Utilities.cs.
- Simplifies MarketInfoReader.cs, OutfittingInfoReader.cs, and ShipyardInfoReader.cs to deserialize directly to the DateTime rather than deserializing to a string and then converting to a DateTime.
> Standardize and fix timestamp parsing

- EDSMResponder/EDSMResponder.cs
- StarMapService/IEdsmService.cs
- StarMapService/StarMapService.cs
Fixes updating EDSM credentials in the EDSM responder UI reloading the EDSM responder but not the associated EDSM credentials in the StarMapService.
I believe that this resolves #1290.
> Fix changes to EDSM credentials not reloading the StarMapService

- CompanionAppService/CompanionAppService.cs
- DataProviderService/DataProviderService.cs
- EDDI/ChangeLog.md
- StarMapService/StarMapService.cs
- Tests/VoiceAttackPluginTests.cs
1. Null-protect `DataProviderService.GetSystemsData()`.
2. Provide a message with the EDSMException for the UI to present.
This can be tested by renaming the SQL DB and changing the EDSM URL in StarMapService.cs to "https://example.com/".
Fixes #1596.
> #1596 fix crash when EDSM down

- JournalMonitor/JournalMonitor.cs
- StatusMonitor/StatusMonitor.cs
Fix #1604 by converting shield state events to be generated via the Status Monitor.
> Fix shield state events not triggering

- VoiceAttackResponder/VoiceAttackVariables.cs
(At present, if the main star is not set then the applicable static VA variables are not reset)
> Reset VoiceAttack variable primary star values when they are not set

- SpeechService/SpeechService.cs
Cereproc voices do not respect `SpeakSsml` (particularly for IPA) but they do handle SSML via the `Speak` method.
Replaces https://github.com/EDCD/EDDI/commit/686b4bfb1bbbbfc355b7b21781e894ff1b455ba7 from PR # 1606.
> Apply workaround for Cereproc IPA support

- SpeechService/Translations.cs
Fix `Sagittarius A*` being pronounced `Sagittarius A minus star` rather than `Sagittarius A star` in some Cereproc voices.
Replaces https://github.com/EDCD/EDDI/commit/a225c4035bec38aa166166b09c2cc2bfcf20abb0 from PR #1606.
> Fix `Sagittarius A*` pronunciation in Cereproc voices

- DataDefinitions/Ship.cs
Add `[JsonProperty("phoneticname")]` to maximize backwards compatibility with prior EDDI versions which used property name "phoneticname" rather than "phoneticName".
(Note that the prior change unfortunately removed ship monitor IPA settings for users that updated their shipyard under 3.5.1)
> Improve backwards compatibility of ship phonetic name

- DataDefinitions/Engineer.cs
- Events/EngineerProgressedEvent.cs
- JournalMonitor/JournalMonitor.cs
- Tests/JournalMonitorTests.cs
Fixes #1629
We currently look for a change in rank first then we look for a change in stage if the rank is unchanged. We ought to change that so that we look for changes in stage and changes in rank separately (so that each can trigger separately when appropriate).
Also tweaks variable descriptions for `EngineerProgressedEvent` and deprecates unused property `rankprogress`.
Note that this does not resolve a second issue identified by #1629. No journal event is written for rank progression after rank 1. It is only recorded in the `EngineerCraft` journal events (which are not timely for EDDI to use in a script).
> Fix `Engineer progressed` reporting rank but not stage when an engineer is unlocked.

- SpeechResponder/Help.md
Fix an incorrect reference to a `Missions route` script in the wiki / help.md. Should be referencing the `Route details` script.
> Fix docs to remove reference to `Missions route` script

- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- SpeechResponder/eddi.ru.json
Checks `event.system` for null (the system is not written to the player journal when we are in the same system as the ship being sold).
Fixes the script unexpectedly ending in "in ____." when event.system is null and system.name is not.
> Fix `Ship sold` script for local ship sales

- SpeechResponder/EditScriptWindow.xaml
- SpeechResponder/Properties/Tooltips.Designer.cs
- SpeechResponder/Properties/Tooltips.resx
- SpeechResponder/ShowDiffWindow.xaml
- SpeechResponder/ViewScriptWindow.xaml
My XAML-based alternative to #1645. 
Implements the ContextMenus in XAML rather than code-behind, which is generally easier to maintain, and I think it's probably more like what the WPF framework designers intended.
> Add static context menus in XAML to Cottle views

- SpeechResponder/Help.md
- SpeechResponder/ScriptResolver.cs
- SpeechService/Translations.cs
Corrects `Star class is {event.stellarclass}.` with some voices (particularly, MS Hazel).
> Engage the ssml function `SayAsLettersOrNumbers` to render spacialised text when ssml is enabled.

- SpeechResponder/ScriptResolver.cs
- SpeechService/Translations.cs
Fixes #1657. Improves handling of complex strings with the `Spacialise()` function (and wherever else our `sayAsLettersOrNumbers` method is applied). Prevents "space" and other whitespace characters from being vocalized.
> Spacialise(): Improve handling of complex strings

- Tests/DataDefinitionTests.cs
- Utilities/ExtensionMethods.cs
- Utilities/Utilities.csproj
- VoiceAttackResponder/VoiceAttackVariables.cs
Resolves #1666 by improving object equality comparison used prior to writing top level variable data to VoiceAttack.
> VoiceAttack Variables: Improve object equality comparison

- SpeechService/SpeechService.cs
- Tests/SpeechTests.cs
- Tests/SpeechUnitTests.cs
Resolves #1655.
Supports escaping for the Cereproc custom tags `<usel>` and `<spurt>`.
Supports escaping for single quoted values inside an ssml tag.
> Fix xml escaping around Cereproc unique ssml tags

- DataDefinitions/Module.cs
- DataDefinitions/Ship.cs
- ShipMonitor/ShipMonitor.cs
Record hull health from the `Ship loadout` event, capture hull and module health from the Frontier API profile, and use the Frontier API profile refresh to update hull and module health before swapping ships. This should ensure accurate voice distortion when voice distortion for ship damage is enabled.
Resolves #1698.
> Ship swapped and hull health

- Events/StarScannedEvent.cs
- Tests/JournalMonitorTests.cs
- Resolves #1696
- Alphabetizes properties of `Star scanned` event for easier lookup / reference.
- Adds undocumented variables:
- alreadydiscovered
- stellarsubclass
- Updates unit testing
> Update `Star scanned` documented properties

- BgsService/BgsFactionData.cs
- Tests/BgsDataTests.cs
PLINQ takes care of all the bookkeeping for us, and splits the collection over a number of tasks determined at runtime based on the number of cores/logical processors on the hardware.
[PLINQ docs](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/parallel-linq-plinq?view=netframework-4.8)
> Prefer PLINQ for parallel processing

- CompanionAppService/CompanionAppService.cs
- DataProviderService/DatabaseStarSystem.cs
- DataProviderService/EddiDataProviderService.csproj
- DataProviderService/StarSystemCache.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- DataProviderService/packages.config
- EDDI/EDDI.cs
- EddiInaraService/InaraService.cs
- Refactors DataProviderService/StarSystemSqLiteRepository` to reduce deserialization and make better use of database column data.
- Implements a short term cache to hold deserialized star system data.
- Refactors startup tasks so that when the home system and squadron system are the same, these are looked up on the same thread to only deserialize once.
> Improve EDDI startup speed

- SpeechResponder/ScriptResolver.cs
- SpeechResponder/SpeechResponder.cs
- Tests/ScriptResolverTest.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
- docs/VoiceAttack-Integration.md
Rebased from #1682.
- Text from the VoiceAttack plugin is now passed through our EDDI's script resolver, making all of EDDI's Speech responder functions invokable from VoiceAttack.
- VoiceAttack-Integration.md updated for clarity and to document previously undocumented plugin functions (particularly `route` and `jumpdetails`). 
@Hoodathunk , I'm not sure that I've got everything right with respect to the  `route` and `jumpdetails` plugin commands so please look these over and let me know if and where I might need to make adjustments.
> Enhance access to the Script resolver from VoiceAttack, improve documentation

- CompanionAppService/CompanionAppAuthenticationException.cs
- CompanionAppService/CompanionAppErrorException.cs
- CompanionAppService/CompanionAppException.cs
- CompanionAppService/CompanionIllegalStateException.cs
- EDDI/EDDI.cs
- EddiInaraService/EddiInaraService.csproj
- EddiInaraService/IInaraService.cs
- EddiInaraService/InaraAuthenticationException.cs
- EddiInaraService/InaraConfiguration.cs
- EddiInaraService/InaraErrorException.cs
- EddiInaraService/InaraException.cs
- EddiInaraService/InaraService.cs
- EddiInaraService/InaraTooManyRequestsException.cs
- InaraResponder/ConfigurationWindow.xaml
- InaraResponder/ConfigurationWindow.xaml.cs
- InaraResponder/EddiInaraResponder.csproj
- InaraResponder/InaraResponder.cs
- InaraResponder/Properties/InaraResources.Designer.cs
- InaraResponder/Properties/InaraResources.resx
- SpeechResponder/ScriptResolver.cs
- Tests/InaraTests.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
Alerts users when Inara credentials are invalid (both with a spoken and visible response). Ceases sending Inara data until credentials are updated. 
Also...
- Add Inara exception classes and update CompanionApp exception classes with missing .ctors
- Handle Inara server response stating that too many requests have been received (with a one hour cool-down until new requests will be accepted)
- Remove EDDI.cs task to intialize the Inara service when starting EDDI (this is now managed through the Inara responder)
- Defined an interface for the Inara service and removed its instance property
- Moved background synchronization from the Inara responder to the Inara service.
- Threads have been replaced with tasks.
- Refactored.
> Inara Update

- DataProviderService/DataProviderService.cs
- EDDI/EDDI.cs
- EDSMResponder/EDSMResponder.cs
- StarMapService/IEdsmService.cs
- StarMapService/StarMapService.cs
Utilize our events rather than the Frontier API to set the EDSM commander name when it is not set. Do not continually request data from the EDSM service while credentials are unconfigured.
Since the 
Resolves #1720.
> EDSM credentials

- DataDefinitions/Ship.cs
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/EddiShipMonitor.csproj
- ShipMonitor/FrontierApi.cs
- ShipMonitor/ShipMonitor.cs
- SpeechResponder/Variables.md
- Tests/ShipTests.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
- docs/VoiceAttack-Integration.md
Resolves #1724.
Update docs for `ship` Cottle variables:
- Health of ship and modules are "last reported" rather than "current"
- Prefer "maxjumprange" over obsolete "maxjump"
- Prefer "maxfuelperjump" over obsolete "maxfuel"
- Prefer "starsystem" over obsolete "system"
Update docs for `ship` VoiceAttack variables to:
- Match variables available to Cottle.
- Add helper variables with hardpoint and compartment counts (for use in VoiceAttack commands which loop through filled modules data).
Replace inefficient calculation of ship distances in the VoiceAttackResponder:
- Replaces inefficient code which deserialized multiple star systems on the VoiceAttack event handler thread to obtain coordinates for stored ships. Ship distances are now either updated during `Location` and `Jumped` events …
> Update `ship` variables and more efficiently handle ship distance calcs

- DataDefinitions/StarSystem.cs
- DataProviderService/DataProviderService.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- EDDI/StarSystemComboBox.cs
- StarMapService/EdsmSystemData.cs
- Tests/EdsmDataTests.cs
- Utilities/Logging.cs
Unplanned null values can cause EDDI to crash in some circumstances (including if EDSM is not available while customizing the commander's home star system). This PR improves handling of those null values.
> More gracefully handle EDSM server unavailable and other network interruptions.

- EDDNResponder/EDDNResponder.cs
The `CarrierJump` event has been added to EDDN schemas (https://github.com/EDSM-NET/EDDN/commit/f03a0857cf4a2b95903d332697b07cc055c6cee7) and we can add support for it simply and immediately.
Change is compatible w/ Elite v3.6.
> Support the Elite v3.7 `CarrierJump` event in the EDDN responder

- EddiInaraService/InaraService.cs
Fixes exceptions like:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at EddiInaraService.InaraService.SendQueuedAPIEvents() in %USERPROFILE%\source\repos\EDDI\EddiInaraService\InaraService.cs:line 302
at EddiInaraService.InaraService.<BackgroundSync>d__33.MoveNext() in %USERPROFILE%\source\repos\EDDI\EddiInaraService\InaraService.cs:line 89
```
by ensuring that the `SendEventBatch` method always returns a list and never returns a null value.
> Fix Inara service exception that can occur when the server does not respond

- SpeechService/Properties/Phonetics.Designer.cs
- SpeechService/Properties/Phonetics.resx
- Tests/SpeechTests.cs
Corrects an exception like
```
SpeechService:speak Speech failed:  System.FormatException: 'phoneme' attribute in 'item' not valid.
at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
at System.Speech.Synthesis.SpeechSynthesizer.Speak(Prompt prompt)
at System.Speech.Synthesis.SpeechSynthesizer.SpeakSsml(String textToSpeak)
at EddiSpeechService.SpeechService.<>c__DisplayClass40_0.<speak>b__0() in %USERPROFILE%\source\repos\EDDI\SpeechService\SpeechService.cs:line 380
```
> Fix invalid IPA for the `Electra` star system

- EDDI/EDDI.cs
- Events/CarrierCooldownEvent.cs
- Events/CarrierJumpCancelledEvent.cs
- Events/CarrierJumpEngagedEvent.cs
- Events/CarrierJumpRequestEvent.cs
- Events/CarrierJumpedEvent.cs
- Events/CarrierPadsLockedEvent.cs
- Events/EddiEvents.csproj
- Events/JumpedEvent.cs
- Events/LocationEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.es.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- SpeechResponder/eddi.pt-BR.json
- SpeechResponder/eddi.ru.json
- Tests/JournalMonitorTests.cs
- Utilities/Constants.cs
From the journal manual, v28:
✔️ 11.1 CarrierJumpedEvent
✔️ 11.4 CarrierJumpRequestEvent
✔️ 11.16 CarrierJumpCancelledEvent
Include synthetic, timer based events for:
- CarrierPadsLockedEvent
- CarrierJumpEngagedEvent
- CarrierCooldownEvent
Please play attention to state tracking when testing and verify that it is robust.
Event scripts are subject to change, please provide feedback.
> Implement carrier jump related events for Elite v3.7

- JournalMonitor/JournalMonitor.cs
- ShipMonitor/ShipRepairedEvent.cs
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- SpeechResponder/eddi.ru.json
- Tests/JournalMonitorTests.cs
- Support parsing a list of repaired modules (as reported when repairing modules at a fleet carrier)
- Make localized module name construction optional by exposing the underlying module objects
- Add appropriate unit tests
- Update `Ship repaired ` script for revised event.
> Update `Ship repaired` event for Elite v3.7.
