EDCD/EDDI

- ChangeLog.md
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/EddiShipMonitor.csproj
- ShipMonitor/ShipMonitor.cs
- ShipMonitor/ShipRepairDroneEvent.cs
- SpeechResponder/eddi.json
Successfully tested in beta. No errors or exceptions in log.
> Add 'Repair drone' event

- DataDefinitions/ModuleDefinitions.cs
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/EddiShipMonitor.csproj
- ShipMonitor/ShipAFMURepairedEvent.cs
- ShipMonitor/ShipMonitor.cs
- SpeechResponder/eddi.json
Fully tested & working in beta, no log errors.
> AfmuRepairsEvent

- EDDI/EDDI.cs
- JournalMonitor/JournalMonitor.cs
> Updates to station services

- EDDI/EDDI.cs
- Events/FileHeaderEvent.cs
- JournalMonitor/JournalMonitor.cs
- JournalMonitor/LogMonitor.cs
- Tests/ShipTests.cs
Now checks file name & "game version" in journal file header to determine whether in beta. Ref. https://github.com/EDCD/EDDI/issues/78
> Revise EDDI's beta detection mechanisms

- EDDI/ChangeLog.md
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/ShipTransferInitiatedEvent.cs
- SpeechResponder/eddi.json
Bugfix for #103
Also update the default cottle script to include transfer price & transfer time when available.
> Bugfix - Ship transfer initiated event

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
> Fix for #141

- DataDefinitions/Body.cs
- EDDI/EDDI.cs
Reviewed & cleaned up changes proposed in PR# 145 to address issue #133.
> Feature update for #133

- EDDI/ChangeLog.md
- SpeechResponder/SpeechResponder.cs
Disables speech for the community goal event while allowing the event itself to be triggered.
> Bugfix-157

- EDDI/ChangeLog.md
- StarMapService/StarMapService.cs
For issue#161. Converted from GET to POST. Also added data for EDShipyard (though EDSM only appears to display the latter of the Coriolis or EDShipyard URIs sent)
> Refined bugfix for EDSM - POST method

- DataDefinitions/ModuleDefinitions.cs
> Add shutdown field neutralizer

- DataDefinitions/Material.cs
- EDDI/ChangeLog.md
> Fix: Material monitor may crash with unknown data

- EDDI/ChangeLog.md
- SpeechResponder/Help.md
- SpeechResponder/ScriptResolver.cs
Crossing off #60 with this one.
> Simple list function

- DataDefinitions/Crime.cs
- EDDI/ChangeLog.md
- Events/BountyIncurredEvent .cs
- Events/FineIncurredEvent.cs
- SpeechResponder/eddi.json
Add humanized crime descriptions per issue #21.
> Better crimes

- EDDI/ChangeLog.md
- Events/EddiEvents.csproj
- Events/JetConeBoostEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.json
> Jetcone boost event

- EDDI/ChangeLog.md
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/EddiShipMonitor.csproj
- ShipMonitor/ModuleArrivedEvent.cs
- ShipMonitor/ModuleTransferEvent.cs
- ShipMonitor/ShipArrivedEvent.cs
- ShipMonitor/ShipTransferInitiatedEvent.cs
- SpeechResponder/eddi.json
Kudos to BumbleB on the forums for suggesting. New feature to address issue #235, adding events when ships and modules arrive at their destinations.
> 'Ship arrived' and 'Module arrived' events

- EDDI/ChangeLog.md
- JournalMonitor/LogMonitor.cs
> Prevent crashes when EDDI hasn't run

- DataDefinitions/BlueprintMaterials.cs
- MaterialMonitor/MaterialMonitor.cs
To be able to go to take the data in EDCD/EDDP is also to have the possibility to have updated datas
> Look for blueprint data in EDCD/EDDP

- EDDI/ChangeLog.md
- Events/MessageReceivedEvent.cs
- JournalMonitor/JournalMonitor.cs
- Tests/JournalMonitorTests.cs
> Multicrew and the 'Message received' event

- DataDefinitions/Commander.cs
- DataDefinitions/EddiDataDefinitions.csproj
- DataDefinitions/Friend.cs
- EDDI/ChangeLog.md
- Events/FriendsEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/Variables.md
- SpeechResponder/eddi.json
Update friends event per #129 and re-enable.
> Update friends event

- EDDI/App.config
- EDDI/ChangeLog.md
- EDDI/EDDI.csproj
- EDDI/MainWindow.xaml
- EDDI/MainWindow.xaml.cs
- EDDI/Properties/Settings.Designer.cs
- EDDI/Properties/Settings.settings
> Remember windows size, position, and minimized / maximized status

- EDDI/ChangeLog.md
- GalnetMonitor/ConfigurationWindow.xaml
- GalnetMonitor/ConfigurationWindow.xaml.cs
- GalnetMonitor/GalnetConfiguration.cs
- GalnetMonitor/GalnetMonitor.cs
> Galnet always on toggle

- DataDefinitions/ModuleDefinitions.cs
> 5th Aegis CG weapons

- DataDefinitions/Economy.cs
- EDDI/ChangeLog.md
- Events/DockedEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.json
> Updates for handling damaged stations

- EDDI/ChangeLog.md
- SpeechResponder/ScriptResolver.cs
Fix for #333.
If there is a problem with "this script", EDDI will now specify which script is affected. It might even tell you a bit about what's wrong. :-)
> EDDI Script resolver error parsing

- EDDI/ChangeLog.md
- StarMapService/StarMapService.cs
> EDSM exception fix

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDDI/EDDIConfiguration.cs
- EDDI/MainWindow.xaml
- EDDI/MainWindow.xaml.cs
> Invalid home systems and stations made clearer in the UI

- EDDI/ChangeLog.md
- EDDI/EDDIConfiguration.cs
> Disable Galnet monitor by default (for Beyond)

- EDDI/ChangeLog.md
- JournalMonitor/JournalMonitor.cs
> Combat bond redeemed hotfix (for Beyond)

- DataDefinitions/EddiDataDefinitions.csproj
- DataDefinitions/Status.cs
- EDDI.sln
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- Events/EddiEvents.csproj
- Events/NearSurfaceEvent.cs
- Events/SRVUnderShipEvent.cs
- Events/SrvTurretEvent.cs
- Events/StatusEvent.cs
- Installer.iss
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/EddiShipMonitor.csproj
- ShipMonitor/ShipFsdEvent.cs
- ShipMonitor/ShipLowFuelEvent.cs
- ShipMonitor/ShipMonitor.cs
- SpeechResponder/SpeechResponder.cs
- SpeechResponder/Variables.md
- SpeechResponder/eddi.json
- StatusMonitor/EddiStatusMonitor.csproj
- StatusMonitor/Properties/AssemblyInfo.cs
- StatusMonitor/StatusMonitor.cs
- StatusMonitor/packages.config
- Utilities/JsonParsing.cs
- Utilities/Utilities.csproj
- VoiceAttackResponder/VoiceAttackPlugin.cs
Feature #371. Many new variables are now available under the `status` object (see updated Variables.md). 
Added the following new uder-facing events:
- `Near surface` event
- `SRV under ship` event
- `SRV turret` event
- `Ship fsd` event
- `Ship low fuel` event
Note: The new status object is also reflected to VoiceAttack. If this PR is approved, the documentation for VoiceAttack will need to be updated per the new values available in the VoiceAttackPlugin.cs `setStatusValues()` method. I've already prepped the update.
> Status.json (for Beyond)

- EDDI/ChangeLog.md
- Events/VehicleDestroyedEvent.cs
- JournalMonitor/JournalMonitor.cs
Fix for #360. Adds FighterDestroyed and SRVDestroyed events for better vehicle state tracking.
> Update ship state tracking (for Beyond)

- DataDefinitions/Government.cs
> Add new government type: 'Prison' for detention centers

- DataDefinitions/ModuleDefinitions.cs
- JournalMonitor/JournalMonitor.cs
& lack of value assignments for certain modules (like voice)
> Fix for #393 - exceptions thrown due to new voice modules in Loadout

- Utilities/Net.cs
Please re-test under VA. Thanks!
> #390 force security protocol to system default

- EDDI/ChangeLog.md
- EDSMResponder/EDSMResponder.cs
- ShipMonitor/ShipMonitor.cs
- StarMapService/StarMapService.cs
> Hotfix for crashes on startup

- DataDefinitions/Crime.cs
- DataDefinitions/Economy.cs
- New economy type: 'Prison'
- New crime type: 'recklessWeaponDischarge'
> Update crime definitions for ED 3.0

- EDDI/ChangeLog.md
- Events/EddiEvents.csproj
- Events/JetConeDamageEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.json
Update jet cone damage with sample event
This event takes place in normal space only... if you see it triggering than there's a good chance that you're going to die... ;-)
> Add jetcone damage event

- DataDefinitions/Material.cs
Also revised descriptions for Guardians ancient data materials per #88.
> Update materials for ED 3.0

- VoiceAttackResponder/VoiceAttackPlugin.cs
Also, moved the string literal for the key to the innermost function, on the Don't Repeat Yourself principle.
If you're happy then please go ahead and merge.
> Initialise the VoiceAttack variable(s) for the Speech Service

- VoiceAttackResponder/VoiceAttackPlugin.cs
> Revert changes to `Set BodyValues` introduced in commit #c1224107.

- DataDefinitions/Status.cs
- StatusMonitor/StatusMonitor.cs
- Tests/StatusMonitorTests.cs
- Tests/Tests.csproj
Simplify and streamline the code for StatusMonitor.cs. Hopefully improving performance a bit.
> Tidy up the status monitor

- EDDNResponder/EDDNResponder.cs
Fix for build error introduced on commit https://github.com/EDCD/EDDI/commit/7c5d6da14a0850da4cc01a26f349f696acbc9abd
> Add an overload method to separate out the dependency injection on the EDDNResponder method.

- EDDI/ChangeLog.md
- Events/EddiEvents.csproj
- Events/FighterRebuiltEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.json
'Fighter rebuilt' event added to the Journal Monitor and the default Speech Responder personality.
> 'Fighter rebuilt' Event

- Utilities/Logging.cs
By comparing everything as lowercase strings and by only checking for unique data if the message matches.
> Improve rollbar de-duplication

- DataProviderService/StarSystemSqLiteRepository.cs
Apparently, the sql database occasionally cannot update because another process has it locked. So we'll update the locking code to prevent this.
> Fix sql database write error

- DataDefinitions/Material.cs
Per rollbar issue #74 & & https://github.com/msarilar/EDEngineer/blob/07bb17950420b920236c8bcc94ea4bb2c33a2f43/EDEngineer/Resources/Data/entryData.json#L1659
> Correct `tg_shipsystemdata` to `tg_shipsystemsdata`.

- DataDefinitions/Material.cs
Reverts EDCD/EDDI#477
We'll revist this after the localization branch is merged.
> Revert "Correct `tg_shipsystemdata` to `tg_shipsystemsdata`."

- EDDI/ChangeLog.md
- ShipMonitor/FrontierApi.cs
- ShipMonitor/ShipMonitor.cs
> Export ship data in `Loadout` format

- EDDI/ChangeLog.md
- SpeechResponder/Help.md
- SpeechResponder/ScriptResolver.cs
- SpeechService/SpeechService.cs
- Tests/SpeechTests.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
Add a new Cottle function "Transmit()" and VoiceAttack plugin action "transmit". Add / revise appropriate unit tests.
**Note that the VoiceAttack documentation on the wiki will need to be updated** to describe this change when it goes live.
> Revised and re-enabled "transmit" voice effect.

- DataDefinitions/CommodityDefinition.cs
- DataDefinitions/CommodityMarketQuote.cs
- DataDefinitions/ResourceBasedLocalizedEDName.cs
- DataProviderService/DataProviderService.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- JournalMonitor/JournalMonitor.cs
> Fixes for commodity definition errors and crashes.

- DataDefinitions/Volcanism.cs
> Fix Cottle null ref. for Volcanism. 

- CargoMonitor/CargoMonitorConfiguration.cs
- CompanionAppService/CommanderConfiguration.cs
- CompanionAppService/CompanionAppCredentials.cs
- EDDI/EDDIConfiguration.cs
- EDDI/EliteConfiguration.cs
- EDDPMonitor/EddpConfiguration.cs
- GalnetMonitor/GalnetConfiguration.cs
- MaterialMonitor/MaterialMonitorConfiguration.cs
- ShipMonitor/ShipMonitorConfiguration.cs
- SpeechResponder/Personality.cs
- SpeechResponder/SpeechResponderConfiguration.cs
- SpeechService/SpeechServiceConfiguration.cs
- StarMapService/StarMapConfiguration.cs
- Utilities/Files.cs
Implement a lock to prevent IO exceptions. 
Rollbar issues 704, 1093, 1095, 1597, 1691, 1698
> Correct IO exceptions reported by Rollbar

- DataDefinitions/StarClass.cs
- DataProviderService/DataProviderService.cs
- EDDI/ChangeLog.md
- Tests/DataProviderTests.cs
- Tests/JournalMonitorTests.cs
> Fix stellar extras & chromaticity not being set

- DataDefinitions/StarSystem.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
> VoiceAttack NullReference exceptions - system state

- ShipMonitor/FrontierApi.cs
- ShipMonitor/ShipMonitor.cs
Hotfix to include Corrosion Resistant Cargo Racks to the ship cargocapacity calculation.
> Corrosion Resistant Cargo Racks & ship cargocapacity

- MaterialMonitor/MaterialMonitor.cs
- VoiceAttackResponder/EddiVoiceAttackResponder.csproj
- VoiceAttackResponder/VoiceAttackPlugin.cs
Fix for https://rollbar.com/EDCD/EDDI/items/3130/
> Material monitor collection synchronization

- SpeechResponder/Properties/SpeechResponder.it.resx
> Correct file reference to eddi.it.json

- DataDefinitions/Ship.cs
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDDI/EDDIConfiguration.cs
- EDDI/MainWindow.xaml
- EDDI/MainWindow.xaml.cs
- EDDI/Properties/MainWindow.Designer.cs
- EDDI/Properties/MainWindow.de.resx
- EDDI/Properties/MainWindow.es.resx
- EDDI/Properties/MainWindow.fr.resx
- EDDI/Properties/MainWindow.hu.resx
- EDDI/Properties/MainWindow.resx
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/ShipLoadoutEvent.cs
- ShipMonitor/ShipMonitor.cs
- SpeechResponder/EddiSpeechResponder.csproj
- SpeechResponder/Variables.md
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.es.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- Tests/ShipTests.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
> Fix Ship value & model not updating in the Ship Monitor

- EDDI/ChangeLog.md
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/ShipLoadoutEvent.cs
- ShipMonitor/ShipMonitor.cs
Fixes #751. Ship value will only be updated if present.
> Make hull and module value optional to event

- DataProviderService/StarSystemSqLiteRepository.cs
Also, less verbose logging when we do this.
> If we re-obtain a star system from the server, remember it.

- EDDI/ChangeLog.md
- VoiceAttackResponder/EDDI.vap
> Fix EDDI.vap minor errors

- DataDefinitions/Ship.cs
- EDDI/ChangeLog.md
Updated change log to share Coriolis instructions on migrating your ships.
Ref. #774.
> Update Coriolis URI per Coriolis dev request.

- EDDI/ChangeLog.md
- EDDNResponder/EDDNResponder.cs
> Remove "wanted" field from data sent to EDDN

- CompanionAppService/CompanionAppService.cs
- DataDefinitions/CommodityDefinition.cs
- DataDefinitions/CommodityMarketQuote.cs
- ShipMonitor/FrontierApi.cs
Report when we encounter unknown ship, module, and commodity definitions, then generate basic definitions from whatever info is available.
Ref. $715 & #741.
> Improve handling of unknown ship, module, and commodity definitions

- EDDI/ChangeLog.md
- ShipMonitor/EddiShipMonitor.csproj
- ShipMonitor/ShipCargoScoopEvent.cs
- ShipMonitor/ShipLandingGearEvent.cs
- ShipMonitor/ShipLightsEvent.cs
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.es.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- StatusMonitor/StatusMonitor.cs
> Add new events for landing gear, cargo scoop, and lights  

- DataProviderService/DataProviderService.cs
> Use Economy.FromName rather than Economy.FromEDName for EDDP data

- VoiceAttackResponder/VoiceAttackVariables.cs
> Prevent error when setting VA version string

- CompanionAppService/CompanionAppService.cs
> Fix InvalidCastException from conditionallyRefreshProfile()

- DataDefinitions/Properties/Superpowers.Designer.cs
- DataDefinitions/Properties/Superpowers.resx
- DataDefinitions/Superpower.cs
- Events/DockedEvent.cs
- Events/JumpedEvent.cs
- Events/LocationEvent.cs
- Tests/JournalMonitorTests.cs
> Add "Guardian" and "Thargoid" superpower definitions

- CargoMonitor/CargoMonitor.cs
- DataDefinitions/Cargo.cs
- DataDefinitions/HaulageAmount.cs
Fix to support 'Chapter 3' game mechanics change with regards to solo delivery missions now using the mission depot
> Support solo delivery missions using the mission depot

- CargoMonitor/CargoMonitor.cs
- DataDefinitions/Haulage.cs
- DataDefinitions/Mission.cs
- DataDefinitions/MissionType.cs
- DataDefinitions/Properties/MissionType.Designer.cs
- DataDefinitions/Properties/MissionType.resx
- MissionMonitor/MissionMonitor.cs
- Tests/MissionMonitorTests.cs
Courtesy of Anthor,
- Added mission type mapping for 'Chained' and 'Welcome' missions.
- Added 'Hack' and 'MassacreThargoid' missions types to mission monitor code, including .resx localization file.
> Additional mission type mapping

- DataDefinitions/SystemState.cs
- EDDI/ChangeLog.md
- EDDPMonitor/ConfigurationWindow.xaml.cs
- EDDPMonitor/EddpMonitor.cs
- EDDPMonitor/Watch.cs
> Fix inability to select states and filters in EDDP for states other than `(anything)`

- EDDI.sln
- EDDI/ChangeLog.md
- ShipMonitor/ConfigurationWindow.xaml.cs
- ShipMonitor/EddiShipMonitor.csproj
- ShipMonitor/IpaResources.xaml
- ShipMonitor/IpaResources.xaml.cs
- ShipMonitor/Properties/ShipMonitor.Designer.cs
- ShipMonitor/Properties/ShipMonitor.resx
- ShipMonitor/packages.config
Opens a small window with helpful links to IPA resources, including the original wikipedia articles.
Fully compatible with i8n.
Resolves #296 and on the to-do list for too long.
> Link to helpful resources for generating IPA pronunciations

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDDI/MainWindow.xaml
- EDDI/MainWindow.xaml.cs
- EDDI/Properties/MainWindow.Designer.cs
- EDDI/Properties/MainWindow.resx
- Utilities/Logging.cs
> Implement log rotation for saner logging

- DataDefinitions/ModuleDefinitions.cs
Fixed Issue #833 Module 'Key not found' errors
> Fixed Module 'Key not found' errors

- EDDI/EDDI.cs
Fix to properly increment 'system visited' after Jump
> Fix to properly increment 'system visited' after Jump

- SpeechService/SpeechService.cs
> Remember voice settings in our synth and only set them again if they need to change.

- DataDefinitions/EddiDataDefinitions.csproj
- DataDefinitions/PlanetClass.cs
- DataDefinitions/Properties/PlanetClass.Designer.cs
- DataDefinitions/Properties/PlanetClass.de.resx
- DataDefinitions/Properties/PlanetClass.fr.resx
- DataDefinitions/Properties/PlanetClass.resx
Correct errors like `2018-11-11T03:07:03 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Metalrichbody in resource EddiDataDefinitions.Properties.PlanetClass`
> Correct edname for metal rich bodies.

- DataDefinitions/EddiDataDefinitions.csproj
- DataDefinitions/Properties/ReserveLevel.Designer.cs
- DataDefinitions/Properties/ReserveLevel.fr.resx
- DataDefinitions/Properties/ReserveLevel.resx
- DataDefinitions/ReserveLevel.cs
Fix errors like: `2018-11-11T00:09:56 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name CommonResources in resource EddiDataDefinitions.Properties.ReserveLevel`
> Correct ednames for system resource levels.

- DataProviderService/StarSystemSqLiteRepository.cs
- EDDI/ChangeLog.md
Resolve #935 by extracting local data from our database and merging it with our updated result.
> Extract local data prior to StarSystem recovery

- DataDefinitions/Material.cs
- EDDI/ChangeLog.md
> Update material rarities

- EDDI/ChangeLog.md
- Events/DockedEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
`Wanted`, `CockpitBreach`, and `ActiveFine`.
> Update `Docked` event to add new new data from journal

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDDI/MainWindow.xaml
- EDDI/MainWindow.xaml.cs
- Removed UI system and faction dependency on squadron power selection
- Added conditional squadron system, allegiance, and faction updating from new 'factions' data in 'FSDJump' and 'Location' journal events.
> More squadron stuff

- EDDI/EDDI.cs
- EDDI/EDDIConfiguration.cs
- EDDI/MainWindow.xaml
- EDDI/MainWindow.xaml.cs
- EDDI/Properties/MainWindow.Designer.cs
- EDDI/Properties/MainWindow.resx
- Improved on UI esthetics
- Added defaults for squadron properties in configuration file
- Added 'No Station' resource for localization
- Sorted various drop down menus
- Various coding efficiency tweaks
> Squadron ui tweaks

- DataProviderService/StarSystemSqLiteRepository.cs
(stale data is better than no data)
> If server StarSystem data is not available, use stale local data

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- JournalMonitor/JournalMonitor.cs
Fix friends not being added to the known friends list.
Resolve #1024.
> Fix `Friends status` event test script not firing.

- DataProviderService/StarSystemSqLiteRepository.cs
- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
Resolves #1014.
Also... fetch but don't create star systems from system names entered by users.
> Use case insensitive sql searches for searching our star systems database

- JournalMonitor/JournalMonitor.cs
- Tests/MissionMonitorTests.cs
Fixed journal monitor exception due to 'Donation' key changed to a string by FDEV. Now using 'Donated' key.
Fixes #1018.
> Donation mission hotfix

- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
- Utilities/Constants.cs
Hotfix to properly update squadron UI elements from 'Location' and 'FSDJump' events data, using the Application Dispatcher.
> Squadron data hotfix

- Events/DockingDeniedEvent.cs
> Update the `Docking denied` test event to resolve an exception

- EDDI/EDDI.cs
> Use event data to synthesize a basic main star when jumping into unexplored systems

- EDDI/PluginSkeleton.xaml.cs
- SpeechResponder/SpeechResponder.cs
Make sure that plugins are fully stopped when they are disabled and fully restarted when they are enabled.
Fixes #1107
> Honor disabled plugin settings

- ShipMonitor/ShipMonitor.cs
Fix errors like https://rollbar.com/EDCD/EDDI/items/11374/?item_page=0&#instances
> Don't assume that ship.maxfuel is set. It may be null.

- CompanionAppService/CompanionAppService.cs
Correction for error observed in eddi.log file.
> Hotfix for 'EconomiesFromProfile' exception

- DataProviderService/DataProviderService.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- EDSMResponder/ConfigurationWindow.xaml.cs
- EDSMResponder/EDSMResponder.cs
Fix sqlite bugs preventing the creation and saving of star systems.
EDSM log synchonization code refactored.
> Fix systems not being saved to the database correctly

- EDDI/EDDI.cs
- Events/EddiEvents.csproj
- Events/SquadronStartupEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/Personality.cs
Added event handler for `SquadronStartup`.
> 'Squadron startup' Event

- CargoMonitor/CargoMonitor.cs
- CompanionAppService/CompanionAppService.cs
- EDDI/EDDI.cs
- EDDNResponder/EDDNResponder.cs
- EDDPMonitor/EddpMonitor.cs
- GalnetMonitor/GalnetMonitor.cs
- JournalMonitor/JournalMonitor.cs
- MaterialMonitor/MaterialMonitor.cs
- MissionMonitor/MissionMonitor.cs
- SpeechResponder/SpeechResponder.cs
- StatusMonitor/StatusMonitor.cs
- Tests/CargoMonitorTests.cs
- Tests/EddnTests.cs
- Tests/MissionMonitorTests.cs
- Tests/ShipTests.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
Post-handling will continue to be asynchronous.
This change is both a general QOL improvement and should help prevent issues with event concurrency / timing.
> Enforce first in first out (FIFO) ordering for event processing. 

- CargoMonitor/CargoMonitor.cs
- Tests/CargoMonitorTests.cs
* Identified and corrected subtle error in Cargo change detection code.
* Amended unit testing.
Resolves #1116
> Hotfix - Cargo change detection

- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- Events/EddiEvents.csproj
- Events/FSDTargetEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/SpeechResponder.cs
- SpeechResponder/Variables.md
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.es.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.ja.json
- SpeechResponder/eddi.json
- SpeechResponder/eddi.ru.json
- VoiceAttackResponder/VoiceAttackVariables.cs
- docs/VoiceAttack-Integration.md
First time coding in C#, first time contributing an OSS project on github. I tried following the contributing guidelines as best I could. I'm open to learning any ways to improve. Thanks for you consideration.
> Add event handler for FSDTarget event

- ShipMonitor/ShipMonitor.cs
- Tests/ShipTests.cs
Data will be written to permanent storage unless this behavior is overriden by bool.
> Add parameters to control whether ships are written to permanent storage during ship tests

- MissionMonitor/MissionMonitor.cs
Changes to event processing using enqueue/dequeue created a 'deadlock' condition between the derived Mission Monitor timed thread, triggering the `MissionExpired` event, and the `MissionExpired` event handler.
Issue corrected by limiting the scope of the mission object `lock` to creating a copy of the `missions` observable collection for use by the timed thread.
This PR should provide some relief for Issue #1159.
> 'Mission expired' deadlock

- GalnetMonitor/GalnetMonitor.cs
- StarMapService/EdsmSystemData.cs
> Prevent the missing Galnet url from crashing EDDI

- EDDI/ChangeLog.md
- SpeechResponder/ConfigurationWindow.xaml.cs
- SpeechResponder/EditScriptWindow.xaml.cs
- SpeechResponder/SpeechResponder.cs
> Fix silent test buttons

- DataProviderService/DataProviderService.cs
- EDDI/ChangeLog.md
- JournalMonitor/JournalMonitor.cs
- ShipMonitor/ShipMonitor.cs
- ShipMonitor/ShipMonitorConfiguration.cs
- Tests/ShipTests.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
> Fix high CPU utilization when loading log files and interacting with the ship monitor

- SpeechResponder/SpeechResponder.cs
- SpeechService/SpeechService.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
> For speech invoked from VA, return after speech completes

- EDDI/ChangeLog.md
- VoiceAttackResponder/VoiceAttackPlugin.cs
> Fix VA invoked speech incorrectly silenced by "disablespeechreponder"

- BgsService/BgsFactionData.cs
- BgsService/BgsService.cs
- BgsService/EddiBgsService.csproj
- BgsService/Properties/AssemblyInfo.cs
- BgsService/packages.config
- DataDefinitions/Faction.cs
- DataDefinitions/StarSystem.cs
- DataDefinitions/Station.cs
- DataProviderService/DataProviderService.cs
- DataProviderService/EddiDataProviderService.csproj
- DataProviderService/LegacyEddpService.cs
- EDDI.sln
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDDPMonitor/EddpMonitor.cs
- Events/DockedEvent.cs
- Events/JumpedEvent.cs
- Events/LocationEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/ScriptResolver.cs
- SpeechResponder/Variables.md
- StarMapService/EdsmFactionData.cs
- StarMapService/EdsmSystemData.cs
- Tests/BgsDataTests.cs
- Tests/DataProviderTests.cs
- Tests/EdsmDataTests.cs
- Tests/JournalMonitorTests.cs
- Tests/Tests.csproj
- Tests/bgsFaction.json
- VoiceAttackResponder/VoiceAttackVariables.cs
Note that the `Faction` definition is revised by this PR to redefine `Faction` (which included system specific variables) and separate system specific variables into a list of subclass `FactionPresence`.
> Add `FactionDetails()` function and endpoint

- GalnetMonitor/GalnetMonitor.cs
At present, we lose track of the last article we read when we are unable to obtain articles (e.g. if a web timeout exception occurs). The variable value `firstUid` is null and that null value is saved to our config files. The Galnet monitor repeatedly loops through the same articles as if they are new.
This PR 
- improves separation between obtaining news items and handling / parsing them. 
- tests to ensure `firstUid` is not null before updating our local config file.
> Prevent the Galnet monitor from resetting

- DataDefinitions/ShipDefinitions.cs
- DataProviderService/LegacyEddpService.cs
> Fix station shipyard data rejections from EDDN

- DataDefinitions/Material.cs
- EDDI/ChangeLog.md
- SpeechResponder/Help.md
- SpeechResponder/ScriptResolver.cs
- SpeechResponder/Variables.md
Implements MaterialDetails() search by star system, returning body details from the body within that system with the highest concentration of the material.
Suggested by @hoodathunk.
> Enhance MaterialDetails() function

- DataDefinitions/EddiDataDefinitions.csproj
- DataDefinitions/Traffic.cs
- DataProviderService/DataProviderService.cs
- EDDI/ChangeLog.md
- SpeechResponder/Help.md
- SpeechResponder/ScriptResolver.cs
- SpeechResponder/Variables.md
- StarMapService/EdsmTrafficData.cs
- Tests/EdsmDataTests.cs
> TrafficDetails() function

- EDDI/EDDI.cs
- EDDNResponder/EDDNResponder.cs
Ref. https://github.com/EDSM-NET/EDDN/pull/88/files
> EDDN touchups, adds the `horizons` bool flag for EDDN data consumers

- CrimeMonitor/ConfigurationWindow.xaml
- CrimeMonitor/ConfigurationWindow.xaml.cs
- CrimeMonitor/CrimeMonitor.cs
- NavigationService/Navigation.cs
- SpeechResponder/ScriptResolver.cs
Found and corrected edge case where Crime Monitor (incorrectly) bypassed updating lone discrepancy reports for fines and bounties paid.
> Fines/bounties paid properly handling discrepancy reports.

- DataDefinitions/AtmosphereClass.cs
- DataDefinitions/Modifications.cs
- DataDefinitions/Properties/Modifications.Designer.cs
- DataDefinitions/Properties/Modifications.resx
```
2019-05-27T06:46:37 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Misc_LightWeight in resource EddiDataDefinitions.Properties.Modifications
2019-05-27T06:46:37 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Sensor_LightWeight in resource EddiDataDefinitions.Properties.Modifications
2019-05-27T06:46:37 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name Sensor_Expanded in resource EddiDataDefinitions.Properties.Modifications
2019-05-27T06:49:01 [Info] ResourceBasedLocalizedEDName:FromEDName Unknown ED name ammoniaoxygen in resource EddiDataDefinitions.Properties.AtmosphereClass
```
> Fix a couple of missing modification definitions

- SpeechResponder/ScriptResolver.cs
Corrected exception in `MaterialDetails()` Cottle function when providing a single parameter.
> MaterialDetails method exception hotfix

- DataDefinitions/ModuleDefinitions.cs
- DataDefinitions/Properties/Modules.Designer.cs
- DataDefinitions/Properties/Modules.de.resx
- DataDefinitions/Properties/Modules.es.resx
- DataDefinitions/Properties/Modules.fr.resx
- DataDefinitions/Properties/Modules.hu.resx
- DataDefinitions/Properties/Modules.pt-BR.resx
- DataDefinitions/Properties/Modules.resx
- DataDefinitions/Properties/Modules.ru.resx
(from the `Bridging the Gap` initiative)
Resolves #1330.
> Add definition for Advanced Multi-Cannon

- DataDefinitions/StarSystem.cs
- DataProviderService/DataProviderService.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- EDSMResponder/ConfigurationWindow.xaml.cs
- EDSMResponder/EDSMResponder.cs
- StarMapService/EdsmSystemData.cs
- StarMapService/StarMapService.cs
- Tests/EddiCoreTests.cs
Fix #1162 issues with system visits becoming desynchronized from EDSM.
> Update tracking of systems visits and EDSM log/comment sync

- DataDefinitions/Station.cs
- DataProviderService/LegacyEddpService.cs
- StarMapService/EdsmStationData.cs
- Tests/JournalMonitorTests.cs
> Handle redundant economies

- DataDefinitions/Ship.cs
- EDDI/ChangeLog.md
- ShipMonitor/ConfigurationWindow.xaml
- ShipMonitor/ConfigurationWindow.xaml.cs
- ShipMonitor/Properties/ShipMonitor.Designer.cs
- ShipMonitor/Properties/ShipMonitor.de.resx
- ShipMonitor/Properties/ShipMonitor.es.resx
- ShipMonitor/Properties/ShipMonitor.fr.resx
- ShipMonitor/Properties/ShipMonitor.hu.resx
- ShipMonitor/Properties/ShipMonitor.ja.resx
- ShipMonitor/Properties/ShipMonitor.pt-BR.resx
- ShipMonitor/Properties/ShipMonitor.resx
- ShipMonitor/Properties/ShipMonitor.ru.resx
> Reinstate export to EDShipyard.

- DataDefinitions/Body.cs
- DataDefinitions/StarSystem.cs
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- Events/BodyMappedEvent.cs
- JournalMonitor/JournalMonitor.cs
- Tests/EddiCoreTests.cs
> Add mapped exploration value and data collected during a scan to the `Body mapped` event

- EDDI/EDDI.cs
- EDDI/MainWindow.xaml.cs
- StarMapService/StarMapService.cs
Use async tasks to improve startup times.
> Startup time

- EDDI/ChangeLog.md
- EDDI/MainWindow.xaml.cs
> Fix EDDI crashes on startup for non-English Windows installations.

- DataDefinitions/StarSystem.cs
- EDDI/ChangeLog.md
- EDDI/EDDI.cs
- Tests/EddiCoreTests.cs
> Resolve Frontier 'bug' causing multiple triggers of 'System scan complete' event

- SpeechService/Properties/Phrases.Designer.cs
- SpeechService/Properties/Phrases.de.resx
- SpeechService/Properties/Phrases.es.resx
- SpeechService/Properties/Phrases.fr.resx
- SpeechService/Properties/Phrases.hu.resx
- SpeechService/Properties/Phrases.it.resx
- SpeechService/Properties/Phrases.pt-BR.resx
- SpeechService/Properties/Phrases.resx
- SpeechService/Properties/Phrases.ru.resx
- SpeechService/Translations.cs
- Tests/SpeechUnitTests.cs
Reduce precision a little bit when describing very large numbers (larger than 10 billion).
Tidy up numbers using scientific notation
Expand test coverage.
> Humanise() tweaks

- EDDI/ChangeLog.md
- SpeechService/SpeechQueue.cs
- Tests/SpeechUnitTests.cs
> Fix crashing in AX conflict zones

- NavigationService/Navigation.cs
- Tests/NavigationServiceTests.cs
Fixed errors in tests and moved them to the 'Integration Testing' suite.
> Hotfix to Navigation testing

- SpeechResponder/ConfigurationWindow.xaml.cs
- SpeechResponder/EditScriptWindow.xaml.cs
Add checks to make sure we aren't reloading scripts unnecessarily.
> Fix speech responder UI slowdowns

- DataDefinitions/ResourceBasedLocalizedEDName.cs
> Ensure subclass constructor has run when using <T>.AllOfThem()

- CargoMonitor/CargoMonitor.cs
Allows processing of multiple commodity changes in a Cargo 'update' event (data from `Cargo.json` file), as identified by Issue #1465 .
> Process multiple commodity changes in Cargo 'update' events

- Events/FSDTargetEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.json
* `FSDTarget` event handling amended for new `remainingjumpsinroute` property.
* Added `Next jump` script to save `remainingjumpsinroute` state for `Jumped` event.
* Revised `Jumped` script to utilize `remainingjumpsinroute` property.
> 3.5 Feature - 'FSDTarget' event 'remainingjumpsinroute' property

- SpeechResponder/Variables.md
- StatusMonitor/Status.cs
- StatusMonitor/StatusMonitor.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
Implement new status properties `hyperspace` and `srv_high_beams`.
> 3.5 Feature - New status properties

- DataDefinitions/EddiDataDefinitions.csproj
- DataDefinitions/Properties/SignalSource.Designer.cs
- DataDefinitions/Properties/SignalSource.resx
- DataDefinitions/SignalAmount.cs
- DataDefinitions/SignalSource.cs
- Events/EddiEvents.csproj
- Events/RingHotspotsEvent.cs
- Events/SurfaceSignalsEvent.cs
- JournalMonitor/JournalMonitor.cs
- SpeechResponder/eddi.de.json
- SpeechResponder/eddi.es.json
- SpeechResponder/eddi.fr.json
- SpeechResponder/eddi.hu.json
- SpeechResponder/eddi.it.json
- SpeechResponder/eddi.json
- SpeechResponder/eddi.pt-BR.json
- SpeechResponder/eddi.ru.json
- Added new script `Surface signals detected` for obtaining details about geological and surface signals on mapped bodies
- Added new script `Ring hotspots detected` for obtaining details about hotspots in a scanned ring
Note:
- The surface signal edname for biological surface signals is speculative / untested.
> 3.5 Feature - Surface signals and ring hotspots

- EDDI/EDDI.cs
- Events/BodyMappedEvent.cs
- Events/RingMappedEvent.cs
- JournalMonitor/JournalMonitor.cs
Add system properties to scan events.
> 3.5 Feature - Scan events system data

- DataDefinitions/Properties/SignalSource.Designer.cs
- DataDefinitions/Properties/SignalSource.resx
- DataDefinitions/SignalSource.cs
* Added `SAA_SignalType_Human` FDEV ID to `SignalSource.cs` and `SignalSource.resx`.
* Fixed resx `identifier warning` with `ListeningPost:#index=1` ID. Now `ListeningPost_index1`.
> 'Human' SAA signal source

- Events/BodyMappedEvent.cs
- Events/BodyScannedEvent.cs
- JournalMonitor/JournalMonitor.cs
> Fix body.shortname

- DataDefinitions/Module.cs
- InaraResponder/InaraResponder.cs
- JournalMonitor/JournalMonitor.cs
Handle modifications with format like
```json
{
"Label": "DamageType",
"ValueStr": "$Kinetic;",
"ValueStr_Localised": "Kinetic"
}
```
> Fix exceptions generated by less typical modifications.

- EDDI/EDDI.cs
Uses journal data in preference to server data as soon as journal data is available.
> Update additional station properties when requesting docking and docking

- VoiceAttackResponder/EDDI.vap
Resolved issue #1535 by fixing EDDI VA profile 'cadmium' typo in materials related queries.
> Fix 'cadmium' typo in EDDI.vap file

- EDDNResponder/EDDNResponder.cs
- Add the `SAASignalFound` event to the EDDN Responder's whitelist.
- Revise the `StripPersonalData` method to be more generic / thorough.
- Disable re-sending events to EDDN during log loading.
- Code cleanups
> Update the EDDN Responder

- DataDefinitions/Properties/StationService.Designer.cs
- DataDefinitions/Properties/StationService.de.resx
- DataDefinitions/Properties/StationService.es.resx
- DataDefinitions/Properties/StationService.fr.resx
- DataDefinitions/Properties/StationService.hu.resx
- DataDefinitions/Properties/StationService.it.resx
- DataDefinitions/Properties/StationService.pt-BR.resx
- DataDefinitions/Properties/StationService.resx
- DataDefinitions/StationService.cs
- DataProviderService/StarSystemSqLiteRepository.cs
- Tests/DataDefinitionTests.cs
The edname `Facilitator` must be translated as `Interstellar Factors Contact` to match against the journal by edname and against EDSM data by invariant name.
> Correct Station Service definition: Facilitator

- EDDI/EDDI.cs
- Events/FSSDiscoveryScanEvent.cs
- Tests/VoiceAttackPluginTests.cs
- VoiceAttackResponder/VoiceAttackPlugin.cs
- VoiceAttackResponder/VoiceAttackVariables.cs
- docs/VoiceAttack-Integration.md
Also adds a mock VoiceAttack vaProxy object for testing voiceattack variable setting methods.
> Add a VoiceAttack system variable for total bodies

- BgsService/BgsFactionData.cs
- BgsService/BgsService.cs
- BgsService/EddiBgsService.csproj
- BgsService/IBgsService.cs
- CrimeMonitor/CrimeMonitor.cs
- CrimeMonitor/EddiCrimeMonitor.csproj
- DataProviderService/DataProviderService.cs
- SpeechResponder/EddiSpeechResponder.csproj
- SpeechResponder/ScriptResolver.cs
- Tests/BgsDataTests.cs
- Tests/DataProviderTests.cs
- Tests/Properties/Resources.Designer.cs
- Tests/Properties/Resources.resx
- Tests/Properties/bgsFactionResponse.json
- Tests/Tests.csproj
- Tests/VoiceAttackPluginTests.cs
Methodology same as EDSM Service mock rest client.
> Uint Testing of BGS Service using Mock Rest Client

- ShipMonitor/ConfigurationWindow.xaml
Resolves #1617.
Replaces https://github.com/EDCD/EDDI/pull/1606/commits/cc2d4a005a99a9bb5878518a2158a9c4bee56740 from PR #1606.
> Fix bad data bind causing ship monitor to crash

- SpeechResponder/ScriptResolver.cs
e.g. {Transmit("{ShipName()} has touched down")}
Also, various code tidy-ups recommended by code analysis
> Enable nested functions when using Transmit()

- DataDefinitions/CommodityDefinition.cs
- SpeechResponder/ScriptResolver.cs
> Fix '...Details()' function exceptions when passed empty strings

- DataDefinitions/CommodityDefinition.cs
Note: commodity has not yet been added to EDDB.
> Add new rare commodity "Apa Vietii" (from the recent Golconda Interstellar Initiative)

- MissionMonitor/MissionMonitor.cs
Fixed 'Identical Key' exception in RNNA calculation.
> Exception in Missions Route calculation

- DataDefinitions/DestinationSystem.cs
- DataDefinitions/Passenger.cs
Fixes pointed out by Aaron Azhari.
> Fix member assignment in copy constructors

- VoiceAttackResponder/VoiceAttackPlugin.cs
Prevents an exception that can occur when exiting VoiceAttack (when trying to release the mutex when the SafeWaitHandle is already closed).
> Improve VoiceAttack shutdown / exit

- SpeechService/SpeechFX.cs
- Ensures that voice effects (except radio effects and audio gain) are completely omitted applied when "level of voice processing" in the Text-to-Speech tab is set to zero.  (Formulas already resulted in zero effects except for a very small echo delay).
- Tidies up method code.
- Resolves #1672 (alternate approach to the same issue).
> Fix voice effects being applied slightly when voice effects should be zero

- CompanionAppService/CompanionAppService.cs
- GalnetMonitor/Properties/GalnetMonitor.Designer.cs
- GalnetMonitor/Properties/GalnetMonitor.de.resx
- GalnetMonitor/Properties/GalnetMonitor.es.resx
- GalnetMonitor/Properties/GalnetMonitor.fr.resx
- GalnetMonitor/Properties/GalnetMonitor.it.resx
- GalnetMonitor/Properties/GalnetMonitor.pt-BR.resx
- GalnetMonitor/Properties/GalnetMonitor.resx
- SpeechService/SpeechService.cs
- Tests/SpeechTests.cs
- Utilities/Constants.cs
- Utilities/Properties/IPA.Designer.cs
- Utilities/Properties/IPA.de.resx
- Utilities/Properties/IPA.es.resx
- Utilities/Properties/IPA.it.resx
- Utilities/Properties/IPA.ja.resx
- Utilities/Properties/IPA.pt-BR.resx
- Utilities/Properties/IPA.resx
I tested all unencrypted http endpoints and replaced them with https equivalents.
I added the security tag out of an abundance of caution: I don't see any security issue in itself.
> Change all external HTTP URLs to HTTPS where available

- SpeechResponder/ScriptResolver.cs
> Fix MaterialDetails() crashing when material is not set

- DataProviderService/StarSystemSqLiteRepository.cs
Resolves #1701.
Wraps json deserialization from the database in try-catch statements. If an exception is thrown, EDDI will use updated star system data without merging in any unreadable old faction reputation and/or body exploration data.
> Speculative fix for database deserialization crash

- DataDefinitions/CommodityDefinition.cs
- DataDefinitions/Economy.cs
- DataDefinitions/Government.cs
- DataDefinitions/Properties/Commodities.Designer.cs
- DataDefinitions/Properties/Commodities.resx
- DataDefinitions/Properties/Economies.Designer.cs
- DataDefinitions/Properties/Economies.resx
- DataDefinitions/Properties/Governments.Designer.cs
- DataDefinitions/Properties/Governments.resx
- DataDefinitions/Properties/StationModels.Designer.cs
- DataDefinitions/Properties/StationModels.resx
- DataDefinitions/Properties/StationService.Designer.cs
- DataDefinitions/Properties/StationService.resx
- DataDefinitions/StationModel.cs
- DataDefinitions/StationService.cs
- Tests/DataDefinitionTests.cs
~~(except as documented in #1736)~~
Change is compatible with Elite v3.6.
> Update definitions for Elite Dangerous v3.7

- StarMapService/EdsmBodyData.cs
- StarMapService/EdsmFactionData.cs
- StarMapService/EdsmStationData.cs
- StarMapService/EdsmSystemData.cs
- Tests/EdsmDataTests.cs
> PLINQ parallel processing for EDSM data

- BgsService/BgsFactionData.cs
- DataDefinitions/FactionState.cs
- DataDefinitions/StarSystem.cs
- JournalMonitor/JournalMonitor.cs
> Fix potentially null faction state objects

- SpeechResponder/ConfigurationWindow.xaml.cs
- SpeechResponder/EddiSpeechResponder.csproj
- SpeechResponder/EditScriptWindow.xaml.cs
- SpeechResponder/Properties/SpeechResponder.Designer.cs
- SpeechResponder/Properties/SpeechResponder.de.resx
- SpeechResponder/Properties/SpeechResponder.resx
- SpeechResponder/Service/ScriptRecoveryService.cs
Tided and rebased PR #1742.
Please submit any translations via [the CrowdIn Project](https://crowdin.com/project/eddi) after the PR is merged.
> JP Venson script recovery 2

- EddiInaraService/InaraService.cs
Ref. https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/blockingcollection-overview
> Implement a producer-consumer threading model with the Inara Service.

- DataProviderService/DataProviderService.cs
- EDSMResponder/ConfigurationWindow.xaml.cs
- EDSMResponder/EDSMResponder.cs
- StarMapService/IEdsmService.cs
- StarMapService/StarMapConfiguration.cs
- StarMapService/StarMapService.cs
- StatusMonitor/StatusMonitor.cs
Implements a producer-consumer model similar to #1770.
> Implement a queuing system for journal events sent through the EDSM Responder

- Events/FSDTargetEvent.cs
- JournalMonitor/JournalMonitor.cs
• Bounty - include localised Target 
• FSDTarget - include StarClass
> Update `FSDTarget` and `Bounty` events for Elite v3.7
